### ISSUE TITLE
Security against code injection?

### ISSUE THREAD

**Issue by n1kt0** [postgraphql/postgraphql#280]
Are there any measures against code injection attacks in postgraphql?

**Comment by calebmer** [comment]
Yep! PostGraphQL is written in TypeScript, and so we leverage that fact to prevent SQL code injection *in the type system*. For SQL injection to even be possible, a developer must deliberately use `sql.raw`, something which will get caught in review. Some links:

- [Our SQL generator utility.](https://github.com/calebmer/postgraphql/blob/d1e1024a52db032461614147a6472ace4a10f61b/src/postgres/utils/sql.ts)
- [An example of the SQL generator in use.](https://github.com/calebmer/postgraphql/blob/d1e1024a52db032461614147a6472ace4a10f61b/src/postgres/inventory/paginator/PgPaginatorOrderingAttributes.ts#L73-L101)

**Comment by benjie** [comment]
v4 is not protected via TypeScript, but is still protected - every part of the query must be generated by the [`makeNode`](https://github.com/postgraphql/graphql-build/blob/7165585cea78c3f1f8192841de4199fdc3db4f2b/packages/pg-sql2/src/index.js#L18-L27) function (we have a number of convenience wrappers for this!) which uses a hidden symbol that cannot be forged via JSON. The query is validated at query compile time and any inconsistencies will cause an error to be thrown.

The SQL generation surface API itself is almost identical to that in PostGraphQL v3.

To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.
