### ISSUE TITLE
Queries fail when table has computed column function and INTERVAL column.

### ISSUE THREAD

**Issue by JesperWe** [postgraphql/postgraphql#309]
The computed column function does not even have to reference the `INTERVAL` column, it is sufficient that the table has a column of `INTERVAL` type for queries that demand the computed column to fail with: 

```
"message": "invalid input syntax for type interval: \" undefined seconds 5 minutes 1 hours undefined days undefined months undefined years\""
```

Looks like Postgrahql is somehow converting the value of the interval column to a string before passing the row to the sql function.

**Comment by benjie** [comment]
@JesperWe Relates to https://github.com/calebmer/postgraphql/issues/265#issuecomment-265736977 - the data is serialized from postgres to JS, and then fed back from JS into postgres again. Fixing #265 should mean that even if we have poor type support for certain columns (such as this) the issue won't be as catastrophic.

**Comment by benjie** [comment]
I believe this will be fixed by v4.
