### ISSUE TITLE
DEBUG="postgraphql*" causes mutation functions to be executed twice

### ISSUE THREAD

**Issue by benjie** [postgraphql/postgraphql#350]
Because it includes `postgraphql:postgres:explain` which calls `explain analyze select...` which actually runs the function. Perhaps we should wrap the explain statement in begin/rollback?

Lost 30 minutes to this.

**Comment by calebmer** [comment]
Oh, interesting. We should only be explaining `SELECT`s (see: https://github.com/calebmer/postgraphql/blob/master/src/postgraphql/withPostGraphQLContext.ts#L204).

We could do a rollback, but perhaps there’s a better way? For example only doing `explain` and not `explain analyse`. Or just removing that feature entirely.

**Comment by benjie** [comment]
Ah - it was with a procedure, which does do a select!

https://github.com/calebmer/postgraphql/blob/master/src/postgraphql/schema/procedures/createPgProcedureMutationGqlFieldEntry.ts#L113

**Comment by calebmer** [comment]
Ah, interesting! 😊

Yeah. I’m all for removing the `explain analyse`s. I never liked how they were included with `postgraphql*`, and since queries are reported anyway getting an explain is always as easy as copy-pasting.

**Comment by benjie** [comment]
Fixed by #354
