### ISSUE TITLE
ngSettings instead of ngOptions in Release Notes for 3.1.0

### ISSUE THREAD

**Issue by mlegenhausen** [postgraphql/postgraphql#412]
@calebmer there is a typo in the release notes for 3.1.0. You wrote `ngOptions` instead of `ngSettings`.

Thanks for Version 3.1.0 😄

**Comment by benjie** [comment]
Thanks for the report @mlegenhausen; this is now fixed 👍 

(Also there was a typo in your reporting of the bug - you wrote `ngOptions`/`ngSettings` instead of `pg*` 😂 )

**Comment by mlegenhausen** [comment]
Oh to much `*g` prefixes in my live :satisfied: but I was consistent in the whole issue :wink:
