### ISSUE TITLE
Support `GRANT (column) ON [TABLE]`

### ISSUE THREAD

**Issue by 0x6368656174** [postgraphql/postgraphql#415]
I need the ability to restrict access at the column level. PostgreSQL allows you to do this using `GRANT (column) ON [TABLE]`. But PostGraphQL does not allow this feature to be used, due to the fact that it chooses immediately the whole line, not the columns:

```sql
select to_json (__ local_0__) as value from "public". "users" as __local_0__ where "id" is not null and true and true and true order by "id" using <limit all
```

And for `GRANT (column) ON [TABLE]` it is necessary that the query be of the form: 

```sql
select json_build_object ($ 1 :: text, __local_0 __. "name", $ 2 :: text, __local_0 __. "login", $ 3 :: text, __local_0 __. "id") as value from "public". "users" as __local_0__ where "id" is not null and true and true and true order by "id" using <limit all
```

@benjie  made a patch that fixes this problem in #340, but it was not accepted in the master.

**Comment by benjie** [comment]
@0x6368656174 #342 builds upon #340 and adds a lot more power (and a number of fixes/tweaks), so it's still open. You can use it now if you like - I do.

**Comment by benjie** [comment]
This is fixed in v4, we now only request the required columns
