### ISSUE TITLE
Roles on functions - Possible misunderstanding

### ISSUE THREAD

**Issue by fabiancook** [postgraphql/postgraphql#416]
I have created this schema:

https://gist.github.com/fabiancook/d68f083cf6950444932ca6799df10160 

I am running this using 

`DEBUG=* postgraphql --connection postgres://role_example_postgraphql:role_example_postgraphql@localhost:5432/database --schema role_example --default-role role_example_unauthenticated --secret secret --token role_example.token`

I expect that you require the role `role_example_a` to access `return_a`, and `role_example_b` to access `return_b`, and any role to access `return_unauthenticated`

When running this mutation (with no bearer token):

```
mutation Mutation {
  returnA(input: {}) {
    token
  }
}
```

I receive:

```
{
  "data": {
    "returnA": {
      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicm9sZV9leGFtcGxlX2EiLCJpZCI6MSwiaWF0IjoxNDkwNzc0OTcyLCJleHAiOjE0OTA4NjEzNzIsImF1ZCI6InBvc3RncmFwaHFsIiwiaXNzIjoicG9zdGdyYXBocWwifQ.uvR-G1H1Zbo6C8lNHXGfOyO4iaP7l_Q4gyp5BhCAfP8"
    }
  }
}
```

I would expect that using only this schema I would never be able to access `return_b`, and only be able to access `return_a` after invoking `return_unauthenticated` and passing the bearer token 

After running 

```
CREATE OR REPLACE FUNCTION role_example.return_b() RETURNS role_example.token AS $$
BEGIN

  IF CURRENT_SETTING('role')::TEXT != 'role_example_b'
  THEN
    RAISE EXCEPTION 'Invalid role claim %', CURRENT_SETTING('role')::TEXT;
  END IF;

  RETURN ('role_example_b', 1)::role_example.token;
END
$$ LANGUAGE plpgsql;
```

And then invoking the endpoint with the above JWT and:

```
mutation Mutation {
  returnB(input: {}) {
    token
  }
}
```

I receive

```
{
  "data": {
    "returnB": null
  },
  "errors": [
    {
      "message": "Invalid role claim role_example_a",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "returnB"
      ]
    }
  ]
}
```

What am I doing wrong here?

**Comment by kenips** [comment]
By default functions created by an admin has execution privileges granted to the public, see: https://www.postgresql.org/docs/current/static/sql-alterdefaultprivileges.html. Specifically, use this line to remove this default after you create your schema:

```
ALTER DEFAULT PRIVILEGES FOR ROLE <admin_role_name> REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
```

**Comment by fabiancook** [comment]
Thanks!
