### ISSUE TITLE
Procedure with enum arrays

### ISSUE THREAD

**Issue by danielbuechele** [postgraphql/postgraphql#417]
I created a procedure accepting an array of enums as argument, like this:
```
CREATE FUNCTION search_articles(type_filter article_type[]) ...
```
which creates a GraphQL field that can be queried like this:
```
searchArticles(typeFilter:[VIDEO,PHOTO])
```

However, this fails in SQL, saying function `searchArticles(text[])` does not exists. The problem seems to be, that the array of enums is translated to a text array. Probably because in JavaScript the argument creates an array `['VIDEO','PHOTO']`, because JavaScript is not aware of existing enums, which is then transformed to SQL. 

On a first look, it looks like we can add some special case here: https://github.com/postgraphql/postgraphql/blob/master/src/postgraphql/schema/procedures/createPgProcedureSqlCall.ts#L36

**Comment by calebmer** [comment]
Another, simpler option would be to add type casting here: https://github.com/postgraphql/postgraphql/blob/master/src/postgres/inventory/type/PgEnumType.ts#L33 or here: https://github.com/postgraphql/postgraphql/blob/master/src/postgres/inventory/type/PgListType.ts#L40

So that it generates either:

```sql
array['x'::article_type, 'y'::article_type]
```

…or:

```sql
array['x', 'y']::article_type[]
```

Please feel free to submit a PR adding this casting! The former is easier and so probably what we want.

**Comment by benjie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Procedure with enum[] arg](https://trello.com/c/HDHRMEBl/17-procedure-with-enum-arg)

**Comment by benjie** [comment]
If someone fancied simply testing if this works in v4 that would be super helpful 👍

**Comment by benjie** [comment]
(I think it will.)

**Comment by benjie** [comment]
Yep; it works:

```
$ createdb test
$ psql test
[test] # create type test_enum as enum('ONE', 'TWO', 'THREE');
CREATE TYPE
Time: 63.477 ms
[test] # create function second(options test_enum[]) returns test_enum as $$ select options[2]; $$ language sql stable;
CREATE FUNCTION
Time: 8.991 ms
[test] # select second(ARRAY['TWO', 'THREE', 'ONE']::test_enum[]);
 second
--------
 THREE
(1 row)

Time: 0.429 ms
$ postgraphile -c postgres://localhost/test
```

```graphql
{
  second(options: [TWO, THREE, ONE])
}
```

```json
{
  "data": {
    "second": "THREE"
  }
}
```
