### ISSUE TITLE
How to restrict clients read,write access

### ISSUE THREAD

**Issue by kamarajuPrathi** [postgraphql/postgraphql#421]
If i have a table example 

there are default methods which come as readExample, updateExample , deleteExample 

and the client as access it using http://abc.com/graphql/query and do modification to that data .

How do i restrict the user ?

**Comment by calebmer** [comment]
By using the Postgres [`GRANT`](https://www.postgresql.org/docs/9.6/static/sql-grant.html) command you can choose who gets to use which commands. By using the [`CREATE POLICY`](https://www.postgresql.org/docs/9.6/static/sql-createpolicy.html) command you can choose which users get to see what data on a row level.

If you haven’t already, make sure to check out our [Postgres schema design tutorial](https://github.com/postgraphql/postgraphql/blob/master/examples/forum/TUTORIAL.md) which explains how to do authentication and authorization in PostGraphQL 😊

If you have any more questions, please let us know!

**Comment by kamarajuPrathi** [comment]
I am not asking about the db grant levels . If the graphql api if exposed as a http request . Then how would restrict these methods is what my question was .

**Comment by calebmer** [comment]
So how to exclude `updateExample` and `deleteExample` from the GraphQL API, or how to throw an error when someone tries to use them?

**Comment by kamarajuPrathi** [comment]
@calebmer exactly

**Comment by calebmer** [comment]
Which one 😊?

To exclude `updateExample` and `deleteExample` you can use `GRANT`s on the user you connect to Postgres with (although that may be broken https://github.com/postgraphql/postgraphql/issues/402), or you can use `--disable-default-mutations`.

To throw an error when some tries to use them then you can use `GRANT`s on the roles you specify in your JWTs or through row level security.

**Comment by kamarajuPrathi** [comment]
To exclude uodateExample and deleteExample from grapqlapi

**Comment by kamarajuPrathi** [comment]
If user has just access to your grapqlapi api . How will postgres grants come in to place

**Comment by calebmer** [comment]
You can’t exclude mutations on a user by user basis. You can throw an error if users who are not allowed to access the mutations try, but GraphQL recommends that you only have one schema for all users.

I believe the `GRANT`s to enable/disable mutations is currently not working. Could you provide the schema you tried so I can see if this is a bug? Follow along with https://github.com/postgraphql/postgraphql/issues/402 just in case.

**Comment by kamarajuPrathi** [comment]
Your Solution would work if i  am trying to have the user information in the same schema . If i have an external user who is authenticated and authorized user to use the api and not allow to do mutations , how would i handle such scenarios

**Comment by calebmer** [comment]
How is your user authenticated? Are they authenticated using the PostGraphQL JWT system, or with another custom authentication system. If you are using a custom authentication system you’ll need to write some custom rules in your application code 😊

**Comment by benjie** [comment]
To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.
