### ISSUE TITLE
Relay transform error ``Maximum call stack size exceeded``

### ISSUE THREAD

**Issue by chris-guidry** [postgraphql/postgraphql#424]
First question: Is there a Relay/React example available for Postgraphql? I haven't found one, but I think it would be very helpful.

I reviewed a similar issue to mine (#373), but his resolution was to change PK's, and it doesn't seem relevant to my issue. Also, I tried @benjie's suggestion to clear the cache, but that didn't work either.

I have followed the Facebook Relay examples, and updated the ViewerQueries.js file based on the PostGraphQL root (replaced "viewer" with "query"):
```
query: () => Relay.QL`query { query }`,
```
In my router, I'm passing ViewerQueries to the component.

In the component I have the following:
```
export default Relay.createContainer(Admin, {
  fragments: {
    query: () => Relay.QL`
      fragment on Query {
        allVariables(condition: {userId:1}) {
          nodes {
            frequency
            userId
          }
        }
      }
    `,
  },
});
```

The resulting error is:

> Error: Relay transform error ``Maximum call stack size exceeded`` in file `.../Admin.js`. Try updating your GraphQL schema if an argument/field/type was recently added.

The following equivalent code runs fine within GraphiQL:
```
query ViewerQueries {
  query {
    ...F0
  }
}

fragment F0 on Query {
  allVariables(condition: {userId: 1}) {
    edges {
      node {
        id
      }
    }
  }
}
```

**Comment by benjie** [comment]
Are you using `--classic-ids`?

```
  .option('-a, --classic-ids', 'use classic global id field name. required to support Relay 1')
```

**Comment by chris-guidry** [comment]
I'm using PostGraphQL with Express so the options are declared in my app.js file using a variable. I updated the variable to set the classicIds to true, but it still didn't work. Also, I'm using react-relay v0.10.0. Should I upgrade that?

```
const postGraphqlOptions = {
  **classicIds: true,**
  graphiql: config.graphql.graphiql,
  watchPg: config.graphql.watchPg,
};
```

**Comment by chris-guidry** [comment]
I was able to get the data to load by creating a Postgres function and calling it in Relay (see below). However, I'm wondering if there is a better way that I should write the GraphQL/Relay statements so that I can use the schema that's already generated by PostGraphQL instead of creating a function? There will be several instances where I essentially need to generate something like:
```
SELECT * FROM someTable WHERE someColumn = x
```


Postgres Function:
```
create function variable_by_user(user_id int) returns public.variable as $$
  SELECT  *
  FROM    variable AS v
  WHERE   v.user_id = user_id
  limit 1
$$ language sql stable;
```
Relay:
```
fragment on Query {
  variableByUser(userId:1) {
    frequency
    frequencyIncrement
  }
}
```

**Comment by benjie** [comment]
When I used to use Relay (before moving to Apollo) I could use all the regular things, but to make it work initially was a huge pain. Most of the issues seemed to be related to Babel's compiling/caching of the (stale, often) GraphQL schema. It required a lot of killing node, clearing the babel caches, then starting node back up again. Good luck!

**Comment by chris-guidry** [comment]
It turns out that I can use allVariables instead of a custom function. I just needed to include the "first" parameter:
```
fragment on Query {
  allVariables(first:1,condition:{userId:1}) {
    edges {
      node {
        id
        frequency
        frequencyIncrement
      }
    }
  }
}
```
