### ISSUE TITLE
Dynamically setting connection string

### ISSUE THREAD

**Issue by jrandeniya** [postgraphql/postgraphql#427]
Is it possible for a URL param to determine which database to connect to when using PostGraphQL as a library? This is what I tried but doesn't work; it just hangs when trying to visit `localhost:3000/user/graphiql`. If you visit `localhost:3000/user/graphql` it throws the expected 'Only POSTrequests are allowed' error.

```js
var express = require('express');
var postgraphql = require('postgraphql').postgraphql;

const app = express();

var services = {
 notification: 'CONNECTION_STRING_TO_NOTIFICATION_SERVICE',
 user: 'CONNECTION_STRING_TO_USER_SERVICE',
};

app.use('/:service', function(req, res, next){ 
 var service = services[req.params.service];
 if(!service) {
  res.status = 404;
  res.send({
   error: req.params.service + ' is not a valid service',
  });
  return;
 }
 req.service = service;
 next();
});

app.use(function(req, res, next) {
 return postgraphql(req.service, 'public', {
  graphiql: true,
  })(req, res, next);
})

app.listen(3000, function() {
 console.log('Listening on 3000');
});
```

**Comment by hkgill** [comment]
+1

**Comment by benjie** [comment]
Referring to: https://github.com/postgraphql/postgraphql/blob/master/docs/library.md

I'd go with two postgraphql instances, so you want something like this (**untested**):

```js
const express = require('express');
const postgraphql = require('postgraphql').postgraphql;

const app = express();

var services = {
 notification: 'CONNECTION_STRING_TO_NOTIFICATION_SERVICE',
 user: 'CONNECTION_STRING_TO_USER_SERVICE',
};

app.use(postgraphql(services.notification, 'public', {
  graphiql: true,
  graphqlRoute: '/notification/graphql',
  graphiqlRoute: '/notification/graphiql',
});

app.use(postgraphql(services.user, 'public', {
  graphiql: true,
  graphqlRoute: '/user/graphql',
  graphiqlRoute: '/user/graphiql',
});

app.listen(3000, function() {
 console.log('Listening on 3000');
});
```

**Comment by calebmer** [comment]
Doing this the way @benjie described is a good idea. Alternatively, you could set up a memoization function. The key thing is to not call `postgraphql` more times then the number of services you have. So if you have two services you want to only be calling `postgraphql` _twice_ and not once for every request. This is because every time `postgraphql` is called PostGraphQL will perform a fresh introspection of your database schema and generate the GraphQL API from that. This is probably why you are seeing some lag 😊

What I think should make the most sense for you (based on your described usecase) is something much like what @benjie described, but you could even make it a little more programatic:

```js
const services = {
 notification: 'CONNECTION_STRING_TO_NOTIFICATION_SERVICE',
 user: 'CONNECTION_STRING_TO_USER_SERVICE',
};

for (const [service, connectionString] of Object.entries(services)) {
  app.use(postgraphql(services.notification, 'public', {
    graphiql: true,
    graphqlRoute: `/${service}/graphql`,
    graphiqlRoute: `/${service}/graphiql`,
  }));
}
```

If you want to swap your PostGraphQL instance out based on some information provided in the HTTP request you could do something like:

```js
const services = {
 notification: postgraphql('CONNECTION_STRING_TO_NOTIFICATION_SERVICE', 'public', {
    graphiql: true,
  }),
 user: postgraphql('CONNECTION_STRING_TO_USER_SERVICE', 'public', {
    graphiql: true,
  }),
};

app.use((req, res, next) => {
  if (someCondition) {
    services.notification(req, res, next);
  } else {
    services.user(req, res, next);
  }
});
```

Let us know how it goes!

**Comment by hkgill** [comment]
Thanks @calebmer and @benjie .
Works pretty great !!!

**Comment by benjie** [comment]
To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.

**Comment by rickq** [comment]
Hello @calebmer, 
I think you have a bug in your code snippet:

```
for (const [service, connectionString] of Object.entries(services)) {
  app.use(postgraphql(services.notification, 'public', {
    graphiql: true,
    graphqlRoute: `/${service}/graphql`,
    graphiqlRoute: `/${service}/graphiql`,
  }));
}
```

There is:
`app.use(postgraphql(services.notification, 'public', {`

but should be:
`app.use(postgraphql(connectionString, 'public', {`

The same is in the documentation:
https://www.graphile.org/postgraphile/multiple-schemas/

Kind regards,
Richard

**Comment by benjie** [comment]
I believe the code is correct; `services.notification` is the relevant connection string:

```js
const services = {
 notification: 'CONNECTION_STRING_TO_NOTIFICATION_SERVICE', // < Connection string
 user: 'CONNECTION_STRING_TO_USER_SERVICE',
};
```

**Comment by rickq** [comment]
Syntactically correct, semantically incorrect ;)

**Comment by benjie** [comment]
Oh I see what you’re saying 👍

**Comment by benjie** [comment]
Fixed in both places :+1:  https://github.com/graphile/graphile.github.io/commit/4cf240f4cc340c8b0fc37012377e19efc0b0fc7f
