### ISSUE TITLE
Custom Mutation/Query

### ISSUE THREAD

**Issue by sciutand** [postgraphql/postgraphql#428]
Let's say I want to create a signupWithFacebook mutation or loginWithFacebook query that receives a facebook token. These can't/shouldn't be implemented as db level procedures since they need to query the facebook api to validate the token. How would I go about implementing something like that?

**Comment by mgallagher** [comment]
So there are a few approaches to interacting with the world outside the database.

1) [LISTEN / NOTIFY](https://www.postgresql.org/docs/9.6/static/libpq-notify.html) - you can have a script running in the background listening for when these mutations occur.

2) Write your mutation functions in something like [Python](https://www.postgresql.org/docs/9.6/static/plpython.html) or [JavaScript](https://github.com/plv8/plv8) and make whatever API calls you need.

3) Use a [foreign data wrapper](https://wiki.postgresql.org/wiki/Foreign_data_wrappers) in combination with something like [Multicorn](http://multicorn.org/). This would be an interesting approach.

I'm sure there's more ways, but these are what seem to come up most frequently when I've had similar questions.

**Comment by benjie** [comment]
👍

Personally, I bypass PostGraphQL for authentication and just use Passport.JS and direct database access.

**Comment by sciutand** [comment]
@mgallagher 
1: I can't use that since the API calls needs to be run before the mutation/SQL query is executed
2: I would have issues with such an approach for the following resons:
- I doubt this scales well in terms of connection usage and resources usage on the db server.
- It would be a security issue to start to open up a db server to outside world. 
- I don't think that writing bare javascript or pyton to interact with external services is a good solution.
3: Looks like it could work but it suffers from the same drawbacks of 2.

Have you guys thought of using hooks/events like `before(mutationname, data)` to be able to manipulate the incoming data before `withPostGraphQLContext` is run?

**Comment by sciutand** [comment]
@benjie 👍  I see that would be the simplest approach I guess.

**Comment by benjie** [comment]
There's been a some discussion around various hooks but no definite plan that I'm aware of.

**Comment by bradleyayers** [comment]
@benjie so do you still use database roles? Or do you implement authz another way?
