### ISSUE TITLE
oracle or odbc connections?

### ISSUE THREAD

**Issue by tomdavidson** [postgraphql/postgraphql#439]
This is too awesome. Thank you for creating postgraphql. Unfortunately, many of our dbs are oracle  (a university).  Is there a legit path to supporting obdc or oracle connections?

**Comment by benjie** [comment]
Not at this time, but please read #87 since expanding to support other databases/systems is somewhere that Caleb would like to take the project.

**Comment by wanghaisheng** [comment]
anything update?
has anyone get other database run?
@benjie @tomdavidson

**Comment by benjie** [comment]
Everything in PostGraphile is very specific to PostgreSQL. Supporting another database would require a lot of database specific work.

Closing this issue as supporting other databases is no longer one of the project's goals.
