### ISSUE TITLE
Additional business logic when resolving requests

### ISSUE THREAD

**Issue by outsidenote** [postgraphql/postgraphql#443]
Most of our planned GraphQL queries are merely CRUD operations, and the capabilities presented in the examples are just what we need.

However, we have some queries which require additional back-end logic (various algorithms and analysis).

Is it possible to support additional logic using postgraphql?
Do I need to separate them to another server?
What is the best practice for this scenario?

Thanks!

**Comment by benjie** [comment]
If the additional logic only relates to data, we have very good support for PostgreSQL functions (which can be written in many languages, including v8 JavaScript):

https://github.com/postgraphql/postgraphql/blob/master/docs/procedures.md

If you need to do something a bit more complex (e.g. it involves network fetches) then I refer you to these issues which may answer your questions:

https://github.com/postgraphql/postgraphql/issues/420
#153

Feel free to reply again if you need more information.

**Comment by benjie** [comment]
V4 will allow you to augment any part of the generated schema via plugins 👍
