### ISSUE TITLE
Multiple data sources

### ISSUE THREAD

**Issue by clayne11** [postgraphql/postgraphql#444]
Is it possible to use PostGraphQL but to merge the server / schema with another server / schema so that the GraphQL endpoint can serve from multiple data sources?

An example would be that most of my API is in PostgresQL, but I have a search function that exists in ElasticSearch. I want to be able to generate 99% of my API with PostGraphQL but to allow merging in my ElasticSearch query so that the implementation / multiple data sources is opaque to the client.

**Comment by brysgo** [comment]
Perhaps this is relevant https://github.com/graphql/graphql-js/issues/490

**Comment by benjie** [comment]
PostGraphQL v4 enables schema extension via plugins 👍

**Comment by devtim123** [comment]
Is there any example of a schema extension plugin?

**Comment by benjie** [comment]
Here’s the docs on it: https://www.graphile.org/postgraphile/make-extend-schema-plugin/

There’s an example one for Stripe on my Patreon feed, I think.

There’s more to come on this front, I’m literally working on it 😁

**Comment by benjie** [comment]
(But basically it works like graphql-tools except it plugs into the plugin system so they types you add are themselves extensible.)
