### ISSUE TITLE
{"errors":[{"message":"Authorization header is not of the correct bearer scheme format."}]}

### ISSUE THREAD

**Issue by jamesallain** [postgraphql/postgraphql#445]
Amazing project!

I'm new to Apollo and Postgraphql. I'm trying to go Serverless, so I'm just running Postgraphql from the cli. I've tried every config I could find, but I still get the error. I get a pre-flight error if I don't include --cors too. 

**error**
 ````
{"errors":[{"message":"Authorization header is not of the correct bearer scheme format."}]}
![error1](https://cloud.githubusercontent.com/assets/15088173/25174563/bf921840-24c5-11e7-90b0-3a61efc2a6a9.PNG)

````

**cli config**
```
postgraphql \
  --connection postgres://nosh_ncp_postgraphql:xyz@localhost:5432/ncp \
  --schema nosh_ncp \
  --default-role nosh_ncp_anonymous \
  --secret keyboard_kitten \
  --token nosh_ncp.jwt_token \
 --cors
````

**gql query**
````
export default  #gql`
	mutation Signup( $input: CreatePersonInput! ) {
	  createPerson( input: $input) {   
	  	person{
                    id
                    name
                   email
       }
    }
}`
````
**Apollo network interface**
````
networkInterface.use([{
	applyMiddleware(req, next) {
		if ( ! req.options.headers) { req.options.headers = {}; }
		const token = Auth.getAccessToken();
		//req.options.mode = 'no cors'
		req.options.headers.authorization = token ? `Bearer ${token}` : null;
		next();
	}
   ###}]);
````

It's working in Graphiql. The Client is definitely seeing the Postgraphql server as I've had a lot of other errors. I think if I get this one, it'll work, which would be unbelievably awesome :)

**Comment by jamesallain** [comment]
![error1](https://cloud.githubusercontent.com/assets/15088173/25174988/0abb295a-24c7-11e7-99df-eda6900ef660.PNG)

**Comment by benjie** [comment]
In the above screenshot you have `authorization: null` which is where the issue likes; it needs to be `authorization: Bearer [TOKEN_HERE]`

**Comment by benjie** [comment]
I think if you change
```js
		req.options.headers.authorization = token ? `Bearer ${token}` : null;
```
to
```js
if (token) {
		req.options.headers.authorization = `Bearer ${token}`;
}
```
it'll work

**Comment by jamesallain** [comment]
That worked. Thanks a lot!
