### ISSUE TITLE
Access nodeId from within postgres?

### ISSUE THREAD

**Issue by jnsone11** [postgraphql/postgraphql#446]
I thought it could be cool to listen/notify on a per node basis to implement subscriptions capable of publishing nested updates. Is it possible to access nodeId's row trigger functions?

**Comment by benjie** [comment]
I'm not sure I understand the question; `nodeId`s are just a base64 combination of the table name and the primary key(s) - so they don't have their own triggers. You can add triggers to the underlying postgresql tables using `CREATE TRIGGER` as usual.

We have some vague plans for subscriptions but no solid plans in place yet.

**Comment by jnsone11** [comment]
Could you point me to the implementation of nodeId generation? This would be helpful.

I've tested the graph.cool implementation of subscriptions and found that update only work on the root node but not for nested nodes. What I'd like to achieve is to update a complete view, even on nested updates.

My idea was to query the subscription data, subscribe to all nodeId's from query result and refire the query on update while the client is still connected.

To achieve this i thought of adding triggers to the tables and foreach row in update pg notify topic/channel nodeId of row. Therefore I need the nodeId from within the trigger. Got me?

**Comment by benjie** [comment]
https://github.com/postgraphql/postgraphql/blob/ade728ed8f8e3ecdc5fdad7d770c67aa573578eb/src/graphql/utils/idSerde.ts#L26-L42

**Comment by benjie** [comment]
To keep things manageable I'm going to close this issue as I think it's solved; but if not or you require further help please re-open it.

**Comment by chris-guidry** [comment]
@jensneuse were you able to create a Postgres function for decoding the nodeId's?

**Comment by benjie** [comment]
You need to base64 decode, and then JSON parse the node ID; in PostgreSQL terms that'd be something like: `decode(id_text, 'base64')::json`. Then you can use the JSON features in PostgreSQL to access the relevant entries within the ID.

**Comment by chris-guidry** [comment]
Thanks @benjie. After I posed the question, I ended up creating a SQL function to decode the base64 value. Here's the function in case anyone else needs it. The function assumes the primary key is one integer column.

```
CREATE OR REPLACE FUNCTION public.node_id_to_id(
  _node_id TEXT
)
RETURNS INTEGER AS $$
DECLARE _node_array TEXT[] = 
  string_to_array(
    convert_from(
      decode(_node_id, 'base64'),
      'UTF8'
    ),
    ','
  );
BEGIN
  RETURN REPLACE(_node_array[2], ']', '')::INTEGER;
END;
$$ LANGUAGE plpgsql stable;
```

**Comment by benjie** [comment]
I think the following might be equivalent, but nicer:

```sql
create function node_id_to_id(_node_id) text returns int as $$
 select ((decode(_node_id, 'base64')::json)->>1)::int;
$$ language sql stable;
```
