### ISSUE TITLE
Primed procedures - search procedure for many to many relationships

### ISSUE THREAD

**Issue by valorize** [postgraphql/postgraphql#454]
Scenario: I have posts and tags. Each post can have multiple tags and each tag belongs to multiple posts. So many-to-many using a postTagXRef table.
In my tag graphql endpoint I can access all posts with `postTagXRefsByTagId { postsByPostId { ... }}`.
But now I want to create a procedure to search for posts which belong to a tag.
My first take was:
```
CREATE FUNCTION tag_search_posts(entry "tag", search text) RETURNS SETOF post
LANGUAGE sql stable
AS $_$

SELECT q.* FROM public.post p
WHERE
  EXISTS(SELECT * FROM public.post_tag_xref pt WHERE p.id = pt.post_id AND entry.id = pt.tag_id) AND
  (p.title ilike ('%' || search || '%') OR p.description ilike ('%' || search || '%'))

$_$;
```
But the parameter `search` is preventing that the tag_search_posts procedure is picked up into the tag graphql type right? Any ideas how to deal with this?

**Comment by benjie** [comment]
I'm a bit too tired to read and fully process your SQL, but it looks like what you've written should show up as a computed column on a tag entry. e.g.

```
[issue454] # create table tag(id serial primary key not null, name text not null);
CREATE TABLE
Time: 6.041 ms
[issue454] # create table post(id serial primary key not null, title text not null);
CREATE TABLE
Time: 3.569 ms
[issue454] # create table post_tag_xref(post_id integer not null references post, tag_id integer not null references tag, primary key(post_id, tag_id));
CREATE TABLE
Time: 5.523 ms
[issue454] # create function tag_search_posts(tag "tag", search text) returns setof post as $$ select post.* from post inner join post_tag_xref on (post_tag_xref.post_id = post.id) where post_tag_xref.tag_id = tag.id and post.title ilike ('%' || search || '%'); $$ language sql stable;
```

```bash
postgraphql -c postgres://localhost/issue454
```

```graphql
{
  allTags {
    edges {
      node{
        id
        name
        searchPosts(search:"foo") {
          edges {
            node {
              id
              title
            }
          }
        }
      }
    }
  }
}
```
  
<img width="832" alt="screenshot 2017-05-03 21 02 06" src="https://cloud.githubusercontent.com/assets/129910/25679047/d675ac6e-3043-11e7-9668-23b1ba0eac3b.png">

**Comment by valorize** [comment]
Thank you very much that helped
