### ISSUE TITLE
Conceptual question: How are the GraphQL queries resolved into SQL?

### ISSUE THREAD

**Issue by AriaFallah** [postgraphql/postgraphql#455]
From what I know, every GraphQL schema has some `resolve` function that actually grabs the data you're looking for. How does PostGraphQL do this? Are the GraphQL queries compiled into SQL somehow? I had difficulty finding it in the code.

**Comment by benjie** [comment]
This may be of interest:

https://github.com/postgraphql/postgraphql/wiki/Code:-how-are-things-like-barByFooId-built%3F

**Comment by benjie** [comment]
Further: in this pull request I re-write most of the SQL queries to be constructed based on the GraphQL query, so that should give you a good idea how things work:

https://github.com/postgraphql/postgraphql/pull/342/files

**Comment by benjie** [comment]
v4 generates queries in a completely different way. I don't have time to document it right now, but it centres around QueryBuilder:

https://github.com/postgraphql/graphql-build/blob/master/packages/graphql-build-pg/src/QueryBuilder.js

Closing this issue to keep things tidy
