### ISSUE TITLE
custom graphql-js query ?

### ISSUE THREAD

**Issue by dmitry-saritasa** [postgraphql/postgraphql#456]
Hi Guys,

is it possible to add additional 'custom' type implemented with reference graphql-js into postgraphql implementation somehow? Or do I need to different qraphql API endpoints to support such functionality?

thanks,
Dmitry

**Comment by benjie** [comment]
Not currently; but check out https://github.com/postgraphql/postgraphql/pull/448

**Comment by benjie** [comment]
PostGraphQL v4 will support this via plugins 👍
