### ISSUE TITLE
How to add a condition where field value is null

### ISSUE THREAD

**Issue by cayman1066** [postgraphql/postgraphql#464]
Fantastic project.  I'm a 15+ year user of PostgreSQL and was delighted to see such a slick implementation of graphQL on top of the database.   I had it working within minutes.

My issue:
I'm just beginning mobile development of my web application.  Part of the platform is a simple recursive message/reply schema (Facebook-like) where a user can post a message and others can reply.  The message table is:

message_id
message_text
group_uuid
[...]
parent_message_id

In normal SQL, I query messages within a group who's parent_message_id IS NULL, and then iterate through each of these original posts to get any replies to each message.

The problem that I'm having is not being able to add a condition to my graphQL query where the parent_message_id = null.  When I do, it retrieves nothing.  Here's what it looks like:

```
{
  allMessages(
    orderBy: TSTAMP_DESC,
    condition: {
      groupUuid: "b09e60fb-2721-41df-98d1-c115f72ad2db",
      parentMessageId: null
    }
  ) {
    edges {
      node {
        groupUuid
        messageId
        messageText
        parentMessageId
        author: userByUserUuid {
          firstName
          lastName
        }
      }
    }
  }
}
```

I can set parent_message_id to any integer and it works as prescribed.  How do a add a condition where the parentMessageId is null?  Or can I?  If not, what work-arounds could you recommend.  

Thanks in advance

**Comment by benjie** [comment]
Hello @cayman1066, and thanks for the compliments!

The `null` thing is a much requested feature, we've a number of issues/PRs about it including #374 and #59

For now, [the workaround](https://github.com/postgraphql/postgraphql/issues/59#issuecomment-222576366) it to define a PostgreSQL function that implements the filtering you need. It's a bit heavy handed, we know, and contribution to the relevant issues with your ideas would be welcome.

**Comment by cayman1066** [comment]
Thanks for the quick response, @benjie,

I'd tried creating a view, but since you can't do a proper join in a view, postGraphQL doesn't pick up any references, and subsequently, doesn't create the necessary queries.  I'll go the function route in the short term, but was trying to avoid that as I'd prefer not to put too much business logic in the DB (a bias from many years as an oracle dba).

I'm new to graphQL, so still just testing for applicability.  postGraphQL is super sweet, and makes graphQL that much more compelling.  Still not 100% sure it can do what I need it to do, mostly because I've got lots of views and materialized views in the DB, and since postGraphQL can't pick up the relationships, then it's not as much of a slam dunk as I was hoping.  Still awesome though!

**Comment by benjie** [comment]
PostGraphQL view relations are also much requested; I believe @tolli81 has some work in progress on this, see #376

**Comment by barbalex** [comment]
I have the exact samt requirement.

I am also very new to relay and graphql so please excuse if my following question es a little naive.

The query I am using is this:

    {
      categoryByName(name: "Fauna") {
        name
        taxonomiesByCategory(condition: {name: "CSCF (2009)"}) {
          nodes {
            name
            taxonomyObjectsByTaxonomyId(condition: {parentId: null}) {
              nodes {
                name
              }
            }
          }
        }
      }
    }

I plan to nest this query a lot deeper.

The examples you reference show how to build a function that enables to query the function top level. Like: 

    {
      myFunction {
        name
        parentId
      }
    }

But how could I integrate this function in above nested query instead of `taxonomyObjectsByTaxonomyId`?

If my understanding is correct this only works with `taxonomyObjectsByTaxonomyId` because there exist references in the data. Which would not be true for `myFunction`.

**Comment by benjie** [comment]
Simple functions operate at the top level, but by following the computed column rules (prefix with table name, take table type as first argument) you can put a function with arbitrary arguments on a record type at any level of the heirarchy.

**Comment by barbalex** [comment]
WOW!!!

crazy

black magic  :-)
