### ISSUE TITLE
Expected id of elements of field `nodes` to be strings.

### ISSUE THREAD

**Issue by vysokyj** [postgraphql/postgraphql#467]
Common database id field is not allowed in Relay modern:
https://github.com/facebook/relay/issues/1682

I suggest to generating id as _id.

**Comment by benjie** [comment]
Try --classic-ids

https://github.com/postgraphql/postgraphql/blob/master/docs/cli.md

**Comment by vysokyj** [comment]
It works! Thank you very much.
I am working on demo based on your forum example: https://github.com/vysokyj/postgraphql-relay-demo

**Comment by benjie** [comment]
Excellent 👍

**Comment by kirkbross** [comment]
> Try --classic-ids
> 
> https://github.com/postgraphql/postgraphql/blob/master/docs/cli.md

Sir Benjie... dead link. I'm using `_id` for my ids but still getting `RelayResponseNormalizer: Expected id on field 'foobar' to be a string.`

**Comment by benjie** [comment]
You need to use —classic-ids. https://www.graphile.org/postgraphile/usage-cli/
