### ISSUE TITLE
does this work with relay modern?

### ISSUE THREAD

**Issue by barbalex** [postgraphql/postgraphql#469]
I am pondering to use

- [create-react-app](https://github.com/facebookincubator/create-react-app)
- postgraphql
- [relay modern](https://facebook.github.io/relay/docs/relay-modern.html)

together.

Seems that create-react-app is not ready [yet](https://github.com/facebookincubator/create-react-app/issues/2001).

What about postgraphql?

**Comment by brysgo** [comment]
I have been using postgraphql with relay modern without issue so far.

**Comment by barbalex** [comment]
yep, looks like this works nicely, so far anyway

thanks for a great tool!

**Comment by benjie** [comment]
Thanks for confirming 👍
