### ISSUE TITLE
[QUESTIONS] New to graphql, coming from making classic RESTful apis in express/postgresql

### ISSUE THREAD

**Issue by johhansantana** [postgraphql/postgraphql#475]
Hello

I've just had a taste on what graphql is and I was amazed but then I tried this project and all of the sudden I was wondering if all this time I was wasting time creating API endpoints lol when I could just use this library to... just do about everything with just one command.

Some doubts I have as I've read a bit of the documentation and all the logic/security is done at the postgres side with functions and what not.

I'm not a very SQL savvy so I was wondering:

1. Is there a way to secure the graphql queries via expressjs or anything that isn't directly via SQL? 
2. In order to use this library successfully one has to learn Postgres SQL queries/functions/etc? 

I ask because I've only used postgres for storing/retrieving data via SQL queries using [pg](https://www.npmjs.com/package/pg) library and done authentication using bcrypt and guid for session tokens.

What I learn from this library as well is that in postgres you can create different schemas and postgraphql will connect only to the `public` one by default so that makes it unable to retrieve the information in the other schemas and you guys handle somewhat security like that if I'm not mistaken.

Also, cudos to the collaborators of this OSS it looks too good to be true.

**Comment by benjie** [comment]
I use a non-default schema as my PostGraphQL schema (not public, never public - it's too often polluted by various extensions/etc which risks leaking information).

You can use PostGraphQL as an express middleware. If you combine this with some kind of query validation (e.g. Using Apollo's persisted queries) you could use a middleware before PostGraphQL to run some security, but it's not really how the library was intended - embrace PostgreSQL!

I'd advise you learn the DB; you can create functions in it using many modern languages (even v8 JS if you want!) but the built in language is suitable for many problems also. Row level security is very cool, but you need to be aware of performance concerns before writing inefficient policies - sometimes it's better to denormalize to squeeze more perf out, if you need it. Of course the DB is blazingly fast so you may not notice ;)

Good luck

**Comment by johhansantana** [comment]
ah I see, thank you for the clarification!
