### ISSUE TITLE
Is it possible to set a condition for a computed field created via function?

### ISSUE THREAD

**Issue by barbalex** [postgraphql/postgraphql#476]
I am trying to get a nested query to work, where I have to filter null values.

This does not seem to work yet and I don't _think_ I can use a function in a deeply nested query (https://github.com/postgraphql/postgraphql/issues/464#issuecomment-304515760).

So I hoped I could use a function to create a computed field containing a boolean. And then use a condition to filter by this field instead of the field with the null values.

My function goes like this:

    CREATE OR REPLACE FUNCTION ae.taxonomy_object_toplevel(taxonomy_object ae.taxonomy_object)
      RETURNS boolean AS
      $$
        select
          case
            when taxonomy_object.parent_id is null then true
            else false
          end
      $$
      LANGUAGE sql STABLE;

And it works nicely to see wheter a taxonomy_object is toplevel (i.e. its parent_id is null) or not.

BUT: When I try to set a condition like this:

    {
      categoryByName(name: "Fauna") {
        name
        taxonomiesByCategory(condition: {name: "CSCF (2009)"}) {
          nodes {
            name
            taxonomyObjectsByTaxonomyId(condition: {toplevel: true}) {
              nodes {
                name
                toplevel
              }
            }
          }
        }
      }
    }

... I get this error: `"Argument \"condition\" has invalid value {toplevel: true}.\nIn field \"toplevel\": Unknown field."`

Filtering by name works nicely:

    {
      categoryByName(name: "Fauna") {
        name
        taxonomiesByCategory(condition: {name: "CSCF (2009)"}) {
          nodes {
            name
            taxonomyObjectsByTaxonomyId(condition: {name: "Reptilia"}) {
              nodes {
                name
                toplevel
              }
            }
          }
        }
      }
    }

So I guess this does not work?

**Comment by benjie** [comment]
You cannot yet filter on computed columns, but you can create your own computed "column" which can actually return a relation (e.g. setof taxonomyObjects) on taxonomies which could take a JSON object as input and do arbitrary filtering you can build yourself.

**Comment by barbalex** [comment]
nice

thanks a lot!
