### ISSUE TITLE
how to create a connection procedure that behaves like "table1ByTable2"

### ISSUE THREAD

**Issue by barbalex** [postgraphql/postgraphql#478]
I am creating something like this:

    CREATE OR REPLACE FUNCTION ae.taxonomy_taxonomy_object_level1(taxonomy ae.taxonomy)
      RETURNS setof ae.taxonomy_object AS
      $$
        SELECT to1.*
        FROM ae.taxonomy_object AS to1
          INNER JOIN ae.taxonomy
          ON ae.taxonomy.id = to1.taxonomy_id
        WHERE
          to1.parent_id IS NULL
      $$
      LANGUAGE sql STABLE;

The nice thing is that `taxonomyObjectLevel1` can be choosen on taxonomy nodes in the graphql query.

What is not so nice is that datasets are not respecting the 1 to n relation from tables `taxonomy` to `taxonomy_object`. So all taxonomy_objects with `taxonomy_object.parent_id` null get listed under all taxonomies.

How can I achieve what postgraphql's `taxonomyObjectsByTaxonomyId` function does?

Maybe I should explain why I am not using `taxonomyObjectsByTaxonomyId`:

Table `taxonomy_object` references itself via `taxonomy_object.parent_id`. I need to connect `taxonomy` to `taxonomy_object` via `taxonomy_object.taxonomy_id` while filtering only taxonomy_objects with null values in `taxonomy_object.parent_id`.

Unfortunately null values can not be filtered using a condition (https://github.com/postgraphql/postgraphql/issues/464). So I need to create a function that filters the null values.

**Comment by benjie** [comment]
You're not using the `taxonomy` object that's being passed into your function, so you're not doing any filtering. See the `AND` clause I've added below:


```sql
CREATE OR REPLACE FUNCTION ae.taxonomy_taxonomy_object_level1(taxonomy ae.taxonomy)
  RETURNS setof ae.taxonomy_object AS
  $$
    SELECT to1.*
    FROM ae.taxonomy_object AS to1
      INNER JOIN ae.taxonomy
      ON ae.taxonomy.id = to1.taxonomy_id
    WHERE
      to1.parent_id IS NULL
    AND
      ae.taxonomy.id = taxonomy_taxonomy_object_level1.taxonomy.id
  $$
  LANGUAGE sql STABLE;
```

**Comment by barbalex** [comment]
works like a charm

thanks a LOT!

**Comment by barbalex** [comment]
I _think_ the fact that this object is passed in and can be used is not well documented.
Or else I just did not realize it.

**Comment by benjie** [comment]
https://github.com/postgraphql/postgraphql/blob/master/docs/procedures.md#computed-columns < This is where the documentation is, a PR to add clarity to that would be welcome 👍
