### ISSUE TITLE
Authentication and authorization on Amazon RDS

### ISSUE THREAD

**Issue by sjensen85** [postgraphql/postgraphql#481]
I setup auth using JWT and postgraphql for my application. Everything is working great on my local database, however when I moved it all to Amazon RDS I am having trouble setting the default value for the jwt_token type.

When first setting up locally I got an error saying:
```unrecognized configuration parameter "jwt.claims.id"```

I found a similar error in a postgrest issue that suggested this:
```alter database app set jwt.claims.id to '0';```

This works great on my local database, but in Amazon RDS I don't have superuser privileges to run this. Does anyone have any experience using auth in RDS?

**Comment by brysgo** [comment]
@benjie mentioned he uses RDS https://github.com/postgraphql/postgraphql/issues/351#issuecomment-278754771. Not sure if he ran into this problem.

**Comment by benjie** [comment]
On Heroku I used to use [this approach](https://github.com/postgraphql/postgraphql/issues/375#issuecomment-299437541):

```
do $$
begin
execute 'alter database ' || current_database() || ' set jwt.claims.person_id to 0';
end;
$$ language plpgsql;
```

However on RDS I use PG 9.6 and the `missing_ok` ([see also](https://github.com/postgraphql/postgraphql/issues/332#issuecomment-276047137)) flag for `current_setting(...)` - I'd recommend the 9.6 way as it's more portable.

**Comment by sjensen85** [comment]
Thanks so much @benjie! This was super helpful.
