### ISSUE TITLE
Third Party API Integration

### ISSUE THREAD

**Issue by dbuarque** [postgraphql/postgraphql#483]
I'm very new with postgraphql and up to now it's awesome to create database abstractions with graphql. But how to handle third parties ? I mean, what is the best approach for third party integration like Stripe or any other API's?

**Comment by mgallagher** [comment]
Hi! Until schema injection in #448 is done / merged, there currently isn't a way to make external API calls within PostGraphQL. Instead, any interaction with the outside world has to be done with Postgres directly. You have a few options there -

1) [LISTEN / NOTIFY](https://www.postgresql.org/docs/9.6/static/libpq-notify.html) - you can have a script running in the background listening for when certain events occur. This would be useful for sending emails, or other actions that don't need to occur within a single request. Lots of slick helper libraries available for this like [node-pg-pubsub](https://github.com/voxpelli/node-pg-pubsub) and [trunk](https://github.com/cyberdelia/trunk).

2) Write your mutation functions in something like [PL/Python](https://www.postgresql.org/docs/9.6/static/plpython.html) and make whatever API calls you need. The issues with this approach though is that it puts additional work onto the database, it'd be difficult to debug, and if you're using a hosted Postgres database like Amazon RDS this just isn't an option at all.

3) Use a foreign data wrapper in combination with something like [Multicorn](http://multicorn.org/). However, this suffers from the same limitations as 2.

Good luck!

**Comment by chadfurman** [comment]
This is easier than you think.

Build a NodeJS Express API that handles endpoints specifically for your extra requests.  Then, use a catch-all endpoint and relay requests/responses to/from Postgraph on the same server.  Node does what Postgraph can't, Postgraph does what you don't want to do in node.  Problem solved.

**Comment by chadfurman** [comment]
Even better, check out https://github.com/postgraphql/postgraphql/blob/master/docs/library.md

**Comment by mgallagher** [comment]
@chadfurman 👍 👍 👍 

I'm not sure why using PostGraphQL as a library and having separate REST endpoints didn't occur to me sooner, but that would be a super easy solution for an external API integration piece I've been working on. Thanks for suggesting that.

**Comment by benjie** [comment]
It will be possible in PostGraphQL v4 to extend the schema with arbitrary plugins, I don't see this functionality being added in v3 so I'm going to close this to keep things tidy.
