### ISSUE TITLE
Return more exception details than just the message?

### ISSUE THREAD

**Issue by zopf** [postgraphql/postgraphql#485]
I am raising exceptions as part of my custom functions in PostgreSQL, and I'd like more details than just the message to be reported by PostgraphQL (for example, the `HINT`, `ERRCODE`, or `SQLSTATE` as specified in the [Postgres docs](https://www.postgresql.org/docs/9.5/static/plpgsql-errors-and-messages.html)).

Here's an example of an exception I'd throw:
```sql
-- check phone number format
if phone_number !~ '^\+[0-9]{8,20}$' then
  RAISE EXCEPTION 'Your phone number must start with a +, contain only numbers, and be at least 8 digits long.'
    USING ERRCODE = '12345';
  return null;
end if;
```

And here is the response that I currently see:
```json
{
  "data": {
    "authenticate": null
  },
  "errors": [
    {
      "message": "Your phone number must start with a +, contain only numbers, and be at least 8 digits long.",
      "locations": [
        {
          "line": 9,
          "column": 3
        }
      ],
      "path": [
        "authenticate"
      ]
    }
  ]
}
```

I'd love there to be a way for PostgraphQL to report the `HINT` or `ERRCODE` that my custom function might send as part of raising an exception.  Is there a good way to have PostgraphQL do so?

One suggestion could be to have optional `"hint"` and `"errcode"` fields in the same context as the `"message"` field.

**Comment by benjie** [comment]
@zopf Looks like it should be possible to add that relatively easily by just modifying the `formatError` method here:

https://github.com/postgraphql/postgraphql/blob/b2155c9a5048b90f9f8c0357eeb2f3084241c60d/src/postgraphql/http/createPostGraphQLHttpRequestHandler.js#L78-L90

If that was wrapped in a CLI option that defaults false, perhaps something like `--extended-errors`, then I'd be happy to see a PR implementing this functionality!

**Comment by zopf** [comment]
Making progress on this today.  Expect a PR soon.

Note: it is theoretically possible to expose any of the fields listed [here in the pg spec](https://github.com/brianc/node-postgres/blob/master/lib/connection.js#L579).

I'll be exposing `code`, `detail`, and `hint`.

**Comment by benjie** [comment]
@zopf Are there security concerns with doing so - revealing too much of your database internals may be risky? I'm wondering if code/detail may be safe but hint maybe only wants to be on development (or opt-in)?

How about we change the `--extended-errors` option from a boolean to a list of fields to be exposed, so people can opt-into it?

Another piece of reference for future issue visitors:

https://www.postgresql.org/docs/9.6/static/plpgsql-errors-and-messages.html

**Comment by benjie** [comment]
(Also: awesome that you're making a PR for this! Thanks!)

**Comment by zopf** [comment]
@benjie PR submitted and passing all checks.  please review :)

**Comment by chadfurman** [comment]
@benjie we should document the way to return error messages to the UI from the DB

**Comment by benjie** [comment]
Yes; feel free to open a separate issue for that, and help with it would be very welcome!

**Comment by chadfurman** [comment]
Which is the repo for the docs again?  is it https://github.com/graphile/graphile.github.io for both postgraphile / graphile?

**Comment by benjie** [comment]
That's correct 👍

**Comment by chadfurman** [comment]
@benjie done
