### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by angelosarto** [postgraphql/postgraphql#486]
I'd like to propose an official docker image as a PR.  I have something running fine locally and I can modify it to make it a good general purpose image.

My proposal for the official docker image would be 

1. Base Image:  Node docker image
1.1. Since postgraphql is mostly a node app this base image probably provides the most up to date and correct base
1. Installation commands:  npm install -g postgraphql  OR  git pull + build + install
1.1. The difference here is the first one is tied only to npm releases while the other will build whatever is in master.   Looking for guidance here :question:
1. EntryPoint:  postgraphql -n 0.0.0.0
1.1.  The -n is needed to expose connections outside of the docker container and by using an entrypoint users of the docker image can just pass options to the command line like this
```bash
docker run -p 5000:5000 postgraphql --connection postgres://someUser:somePassword@myserver.com:5432/mygraphqlDB --cors --jwt-audiences postgraphql,mycustomaud --jwt-role https://some_app/app_metadata,user
```

I can also setup an account on dockerhub for this so people can pull without building locally.  I have setup automated builds on docker hub/docker cloud before.

Any interest in me doing this - and should I tie it to the npm released version or to master?

**Comment by benjie** [comment]
Please make sure you've read through #52, #75, #109 and #113 before commencing any work on this. Anything Caleb says there overrides what I say below (as I have not read through those issues for a while).

Can we tie the docker image generation and upload into CI?

1. Node base ✅ 
2. Can we use the compiled code from CI? If not then using postgraphql from npm seems wise (so long as the node_modules cache is cleared each time - we've had issues with this in the past) - could we use [tags](https://docs.npmjs.com/getting-started/using-tags) with this, e.g. `npm install postgraphql@next`?
3. Listen on every interface ✅ 

I'm all for ease of deployment (PostGraphQL is all about getting stuff started quickly!) so I think if people want to install it from Dockerhub we should enable that.

**Comment by angelosarto** [comment]
I looked through those issues and I guess what I am proposing first is a production (end-user) docker image.   

A developer one is a nice goal to add in the future but it ends up making some assumptions about how each developer will develop and you end up going down the path of do we check-in the eclipse or intellij project file...(IMHO)

On a separate PR I will propose an example docker-compose in the examples directory that basically will be a single command postgres + postgraphql environment.


Regarding question 2:  we can use the tags from git to perform actions as part of the docker image build; however I don't think we can use the results of the travisCI builds directly.  
That leaves us with two options:
1. Install from npm
1. re-build on docker's build image after the CI and install locally.

Installing from npm seems like a good idea, _**But**_ the issue is I don't think we are pushing all of the builds automatically to npm currently.  Looking at the one that is currently there its `published 3 months ago`. 

I guess my question is this - is there any plan to automate the release to NPM?  

- If there is then we can curl an endpoint after it pushes the package to npm and that endpoint will start the docker build.
- If pushing every build result to NPM is something we are not interested in the best plan is simply re-execute the build step as part of the docker build.  The other advantage here is we can create docker images of every tag and latest pretty easily - but they will be GitHub tag aligned not necessarily npm aligned...

@benjie @calebmer let me know the direction to go here if you have a preference (and modify the build script to push to npm if thats what you want) o.w. I think I will have to go with the re-build on docker for now.

**Comment by benjie** [comment]
For now a rebuild on docker would be fine; but I would love to have master builds auto-pushed to npm (using an npm tag) because it's not currently possible to install the git version of postgraphql due to needing to compile all the typescript.

**Comment by benjie** [comment]
I'm closing this in favour of #496
