### ISSUE TITLE
query function returning table not turning up in GraphiQL

### ISSUE THREAD

**Issue by barbalex** [postgraphql/postgraphql#491]
I am happily working with functions returning sets of table rows.

Now I created [a query that returns a table](https://github.com/barbalex/ae2/blob/master/src/sql/pco_properties_by_categories.sql).

This query (pcoPropertiesByCategories) does not seem to turn up in http://localhost:5000/graphiql even though I am running `postgraphql -c postgres://user:password@localhost:5432/ae -s ae --cors --watch`.

I'm sure this is a blatant mistake on my side but what could it be?

**Comment by benjie** [comment]
I believe the issue is that you've effectively declared an anonymous table. If you were to create an actual table with that shape and return that it would work.

```sql
CREATE TABLE foobar(property_collection_name text, property_name text, jsontype text, count bigint);
CREATE OR REPLACE FUNCTION ae.pco_properties_by_categories(categories text[])
  RETURNS foobar AS
...
```

**Comment by benjie** [comment]
(Basically it's a failure in our type creation from introspection.)

**Comment by barbalex** [comment]
Yep, that did it.

Although I could not get it working by returning the table `RETURNS ae.pco_properties_by_category AS`.

It only worked properly once I returned a setof: `RETURNS setof ae.pco_properties_by_category AS`.
Which meant I had to call my function different from the table.

Feel free to close this issue. I left it open because it sounds like this could be solved with better type creation from introspection.

Thanks a lot for this project and your great help!

**Comment by benjie** [comment]
Returning a single row should work (does for me with various functions) but you have to be careful names don't conflict.

**Comment by chris-guidry** [comment]
I ran into this same issue and found that creating a type and using, `RETURNS setof my_type` worked as well.

**Comment by pyramation** [comment]
When using `postgraph@next`, I'm running into this error. I tried to create a table, and this works, however, it feels extremely superfluous to have a table that never is used to store any data, so I'd like to try and use a type. I tried to create a type, and am running into the issue even if the type is defined. Any clues?


```
$ DEBUG=graphile-build-pg:warn yarn start

Failed to add function 'myschema.myfunction'; run with 'DEBUG="graphile-build-pg:warn"' to view the error
  graphile-build-pg:warn Error: Do not have a connection type 'MyschemaTypesConnection' for 'Mytype' so cannot create procedure field
  graphile-build-pg:warn     at makeProcField (/path/to/my/project/node_modules/graphile-build-pg/src/plugins/makeProcField.js:133:17)
  graphile-build-pg:warn     at introspectionResultsByKind.procedure.filter.reduce (/path/to/my/project/node_modules/graphile-build-pg/src/plugins/PgQueryProceduresPlugin.js:69:33)
  graphile-build-pg:warn     at Array.reduce (native)
  graphile-build-pg:warn     at PgQueryProceduresPlugin.builder.hook (/path/to/my/project/node_modules/graphile-build-pg/src/plugins/PgQueryProceduresPlugin.js:25:12)
  graphile-build-pg:warn     at SchemaBuilder.applyHooks (/path/to/my/project/node_modules/graphile-build/src/SchemaBuilder.js:288:20)
  graphile-build-pg:warn     at fields (/path/to/my/project/node_modules/graphile-build/src/makeNewBuild.js:433:40)
  graphile-build-pg:warn     at resolveThunk (/path/to/my/project/node_modules/graphql/type/definition.js:159:40)
  graphile-build-pg:warn     at defineFieldMap (/path/to/my/project/node_modules/graphql/type/definition.js:321:18)
  graphile-build-pg:warn     at GraphQLObjectType.getFields (/path/to/my/project/node_modules/graphql/type/definition.js:282:44)
  graphile-build-pg:warn     at Object.newWithHooks (/path/to/my/project/node_modules/graphile-build/src/makeNewBuild.js:573:18) +0ms
```

**Comment by benjie** [comment]
The error's here:

https://github.com/graphile/graphile-build/blob/d2da24040a6a352679b5985b4829634f32396e7a/packages/graphile-build-pg/src/plugins/makeProcField.js#L130

Looks like you've got a `RETURNS SETOF mytype` function? We can't find a connection with the relevant name:

https://github.com/graphile/graphile-build/blob/d2da24040a6a352679b5985b4829634f32396e7a/packages/graphile-build-pg/src/plugins/makeProcField.js#L126-L128

**Comment by benjie** [comment]
(Oops, didn't mean to send that)

Which should have come from here:

https://github.com/graphile/graphile-build/blob/d2da24040a6a352679b5985b4829634f32396e7a/packages/graphile-build-pg/src/plugins/PgTablesPlugin.js#L253-L297

Have a poke around at the conditions and see what you're hitting up against. This is a bug though, most likely. Please provide a minimal pg_dump and `postgraphql` call (either command line or as express middleware) to reproduce the issue. Oh, and file it as a new issue 👍

**Comment by chadfurman** [comment]
It's also important to make sure the type is in the same schema

**Comment by pyramation** [comment]
so I tried to create a reproducible test case. I just finished putting together an entire repo ready to share and then all tests pass in basic scenarios 😂

Is it possible that it is not defined yet as a result of a dependency resolution issue? For example, does graphile/postgraphql just take introspection results as ordered and create the graphql types/schemas? or do you do some type of introspection on the types and see if they've yet to be loaded?

**Comment by benjie** [comment]
Sharing the shape of the function and the shape of the types it references would be valuable - we don't need the function body (replace it with `select null`). Also you can rename the function and the types:


```sql
create schema a;
create schema b;
create type a.blah as (
  id int,
  qux text
);
create function b.foo() returns setof a.blah as $$
  select null;
$$ language sql stable;
```

I suspect the schemas you use are important here.

**Comment by pyramation** [comment]
If I literally take the exact functions out of the codebase, keeping the shape identical with the actual code, the isolated case passes. So something outside of the particular schema/types is tripping up the system. We may need to coordinate a pg dump of some sort to find out what's happening

**Comment by benjie** [comment]
If you do a full pg_dump and restore to a fresh DB, does it still happen? You have me intrigued. Even if it turns out to not be a bug, please share because I'd love to provide a hint to users who get the same issue. But I'm still thinking it's a bug.

**Comment by pyramation** [comment]
Currently I have another app reading the exact same database and it has no issues. So there's something in the node or environment of this particular project causing issue bc introspection from a clean postgraph install on same creds works. Still digging... ;)

**Comment by chris-guidry** [comment]
@pyramation have you checked to see if there are multiple instances of the function? I have run into issues after changing the input parameters where I end up with two functions that have the same name, but different input parameters and PostGraphQL doesn't let me use either one.

Also, does the other app have different permissions? It could be that it's not seeing the same objects and thus avoiding the issue.

**Comment by pyramation** [comment]
OK, so thanks to @benjie 's advice to check yarn vs npm, etc., I was able to clear my yarn cache, and after hitting this https://github.com/postgraphql/postgraphql/issues/550 issue, I pinned my `pg` to 6.4.0 and it works now!

**Comment by benjie** [comment]
🎉

**Comment by barbalex** [comment]
I just tried to use types instead of creating superfluous tables too and it worked!
Thanks a lot to @pyramation
