### ISSUE TITLE
Reference another schema?

### ISSUE THREAD

**Issue by dthree** [postgraphql/postgraphql#514]
Can I reference another schema? This doesn't seem to be working.

```
CREATE TABLE "schema_a"."foo"
(
  id bigserial NOT NULL,
  name text NOT NULL,
  from_org_id bigint NOT NULL references schema_b.org_ref(id),
  to_org_id bigint NOT NULL references schema_b.org_ref(id),
  created_by bigint NOT NULL,
  created_on date NOT NULL,
  modified_by bigint,
  modified_on date,
  active boolean DEFAULT '1',
  CONSTRAINT foo_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE   
);
ALTER TABLE "schema_a"."foo"
  OWNER TO foo;

COMMIT;
```
When viewing this in GraphiQL, I get `allFoos`, but no reference to `schema_b`.

---

It seems like `postgraphql` only deals with one schema. Worst case, I can create a new server per schema. But if they can't cross-reference, that's a dealbreaker :(

I really hope they can, because this is a great project!

**Comment by herbertpimentel** [comment]
Did you tryed use --schema flag available on client tool ?

https://github.com/postgraphql/postgraphql/blob/master/docs/cli.md

**Comment by dthree** [comment]
Oh wow I totally missed!!!

Working now, thanks!

**Comment by benjie** [comment]
@dthree If you think that could be made clearer in the docs, please raise a PR. IMO everyone should be using a non-default schema so the schema option is a pretty important thing to discover!

**Comment by dthree** [comment]
@benjie sure :)

I definitely wasn't using `public` and got that you could pick another one, but I didn't see that you could pick more than one anywhere. I even re-watched the video for a third time to see. It honestly seemed like this was a flaw that wasn't being mentioned intentionally, clearly not the case!

**Comment by benjie** [comment]
@dthree In that case, a simple mod to the docs so that the example contains something like `--schema data,computed_columns` or similar should be sufficient?
