### ISSUE TITLE
Cut a release for July, 2017

### ISSUE THREAD

**Issue by doeg** [postgraphql/postgraphql#517]
Hi there,

First of all, thank you so much for such a great library. I use postgraphql all the time in my personal projects and it's a huge time-saver, not to mention the documentation is above and beyond. 

Would it be possible to cut a new release for July 2017? Specifically, I'd love to use https://github.com/postgraphql/postgraphql/pull/480. 

(I'm currently using the repo pinned to current master in my `node_modules`, however it requires an extra `yarn install & yarn build` from within `node_modules/postgraphql`, which complicates automatic provisioning and deployment.)

Thank you very much,
-- Sara

**Comment by benjie** [comment]
It's on my todo list 👍  I have to check that all the fixes we merged don't break anything - especially GraphiQL.

In the mean time, maybe the v4 alpha (#506) would serve your purposes? I'm pretty sure it includes that fix:

`npm install postgraphql@next`

**Comment by doeg** [comment]
Awesome, `postgraphql@next` is working like a charm! ✨ Thank you SO much for your super quick reply, and for all of your (and the other maintainers') amazing work. 

P.S. I'd love to send over some $$$ to say thank you & buy the collective maintainer's a coffee or something... have you considered starting a [Gratipay](https://gratipay.com/about/)? Otherwise, I'd love to donate to a charity in PostgraphQL's name. ❤️

**Comment by doeg** [comment]
(P.P.S. Feel free to close this issue if it's not helpful for your release flow. My issue has been solved. 👍)

**Comment by benjie** [comment]
@doeg Thanks for the push; I've set one up for review 👍  https://github.com/gratipay/project-review/issues/507

**Comment by benjie** [comment]
v3.3.0 is now released 👍

**Comment by doeg** [comment]
Thank you!!! 🎉 🎉 🎉

**Comment by mattbk** [comment]
@doeg, the Gratipay project has been approved: https://gratipay.com/PostGraphQL/
