### ISSUE TITLE
Void return type error running postgraphql

### ISSUE THREAD

**Issue by graphqlgirl** [postgraphql/postgraphql#524]
I have a postgres database on RDS and I'm running into the following when I run postgraphql 

Error: Procedures with a void return type are not allowed in GraphQL queries.
    at createPgSingleProcedureQueryGqlFieldEntry  (.../node_modules/postgraphql/src/postgraphql/schema/procedures/createPgProcedureQueryGqlFieldEntry.ts:40:11)
at Object.createPgProcedureQueryGqlFieldEntry [as default] (.../node_modules/postgraphql/src/postgraphql/schema/procedures/createPgProcedureQueryGqlFieldEntry.ts:24:9)
(.../node_modules/postgraphql/src/postgraphql/schema/createPostGraphQLSchema.ts:131:81)

I have not created any functions that return void. 

I'm using postgraphql as an express library as done here  https://github.com/postgraphql/postgraphql/blob/607f6629986735139e2b77d5a9b1143846c4f691/docs/library.md

any thoughts as to what may be happening?

**Comment by benjie** [comment]
My guess would be one of your extensions has installed a function like that into the public schema. To confirm, run "\df" from psql, if this is the issue I strongly recommend using an alternative schema for PostGraphQL.

Do you get the same issue with the v4 alpha? "npm install postgraphql@next"

**Comment by graphqlgirl** [comment]
Hi Benjie - thanks for the quick reply! Think you're correct that a recently installed extension is the cause..

with V4 alpha I get a similar error:
Error: Schema query must be Object Type but got: undefined.
  at invariant (.../node_modules/graphql/jsutils/invariant.js:19:11)
    at new GraphQLSchema (.../node_modules/graphql/type/schema.js:72:88)

Thanks

**Comment by eric-taix** [comment]
Hi Benjie,

I confirm this issue. 
In my case PostGIS extension is installed: this is a "legacy" application which uses geospacial features of PostGres and I can't remove extension. Any idea to solve this issue without removing the extension ?

**Comment by benjie** [comment]
Currently we do not have a workaround; in V4 you could potentially install a replacement for the introspection plugin that filters out the PostGIS extension but that may be a fair amount of work.

It might just be a case of automatically ignoring stable functions that return void (though I'm not sure what the point of a stable function that returns void is... I'm guessing it's not really a stable function?)

**Comment by deinspanjer** [comment]
What about either reinstalling the extension into a different schema, or using a schema other than `public` for hosting postgraphql?

**Comment by benjie** [comment]
Both of those would work; I strongly recommend using an alternative schema for PostGraphQL data/functions because the public schema is often polluted, and you don't really want those extra methods being exposed to your GraphQL clients. Many (but not all) extensions will allow you to set a different namespace to install into, but then you must make sure that new namespace is part of your search_path otherwise you have to give the fully qualified method name each time.

**Comment by benjie** [comment]
@eric-taix I'd love to know if the latest PostGraphQL v4 solves your issue? `npm install postgraphql@next`

**Comment by benjie** [comment]
@graphqlgirl Similarly, I think the issue you listed above should be fixed by now?

**Comment by graphqlgirl** [comment]
yep thanks @benjie, it's been fixed -- if you've updated PostGraphQL v4, haven't checked that out yet

**Comment by eric-taix** [comment]
@benjie I tried postgraphql 4.0.0-alpha2.8 and it works with the postgis extension : I'm now able to request my database and Geometry columns with GraphiQL.

Thanks so much for the hard work

**Comment by benjie** [comment]
Awesome. I'm going to close this then 👍
