### ISSUE TITLE
unable to query array of enum type

### ISSUE THREAD

**Issue by stlbucket** [postgraphql/postgraphql#527]
```
CREATE TYPE my_enum_type AS ENUM (
  'Val1',
  'Val2'
);
```
```
CREATE TABLE my_table (
  id uuid UNIQUE NOT NULL DEFAULT uuid_generate_v1(),
  name text NOT NULL,
  my_enums my_enum_type[] NOT NULL,
  CONSTRAINT pk_my_table PRIMARY KEY (id)
);
```

... I've not tried to save this with auto-generated mutation.  instead i use a function, and that mutation will accept an array like [Val1, Val2] and save it properly.

This works:
```
query {
  myTableById(id: "SOME-UUID-VALUE") {
    id
    name
  }
}
```

However, this will not work:
```
query {
  myTableById(id: "SOME-UUID-VALUE") {
    id
    name
    myEnums
  }
}
```

Error is:
```
{
  "errors": [
    {
      "message": "Expected Iterable, but did not find one for field MyTable.myEnums.",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "myTableById",
        "name",
        "myEnums"
      ]
    }
  ],
  "data": {
    "myTableById": null
  }
}
```

**Comment by stlbucket** [comment]
looks like the error is being thrown from graphiql, line 20103:

/**
 * Complete a list value by completing each item in the list with the
 * inner type
 */
function completeListValue(exeContext, returnType, fieldNodes, info, path, result) {
  (0, _invariant2.default)((0, _iterall.isCollection)(result), 'Expected Iterable, but did not find one for field ' + info.parentType.name + '.' + info.fieldName + '.');

**Comment by benjie** [comment]
@stlbucket As I know you're one of the people using PostGraphQL v4 sometimes: can you clarify if this is a v3 or v4 issue?

**Comment by stlbucket** [comment]
v4

**Comment by benjie** [comment]
Closed in favour of: https://github.com/postgraphql/graphql-build/issues/18
