### ISSUE TITLE
Create "postByAuthorId" query automatically in the forum example

### ISSUE THREAD

**Issue by knqyf263** [postgraphql/postgraphql#528]
Hi! Thank you for the awesome tool!

I've read the following example.
https://github.com/postgraphql/postgraphql/tree/master/examples/forum

I have a simple question.
What should I do if I want to retrieve all posts from a specific user?
If it is not my misunderstanding, `postgraphql` automatically creates `allPosts` and `postById` queries.
Is there a way to create `postByAuthorId` query automatically?

Shoud I `CREATE FUNCTION` by myself?

I'm sorry about the rudimentary question.
Thanks!

**Comment by benjie** [comment]
I think you could use the "condition" filter on allPosts to limit by authorId?

**Comment by knqyf263** [comment]
Oh! This is what I was looking for!
Thank you for the answer!

It's really a useful tool.
Many Thanks.

**Comment by knqyf263** [comment]
@benjie 
I'm sorry. I have one more question.

As you said, I can use `condition: {authorId: 1}`. Thank you very much!
In addition, is it possible to specify multiple authorIds like `condition: {authorId: [1, 2]}`?

```
"message": "Argument \"condition\" has invalid value {serverId: [1, 2]}.\nIn field \"serverId\": Expected type \"Int\", found [1, 2]."

**Comment by benjie** [comment]
No, for that you'll need to write a custom function, something like:

```sql
Create function posts_by_author_ids(author_ids integer[]) returns setof posts as $$
Select * from posts where author_id = any(author_ids);
$$ language sql stable;
```

Written on my phone, forgive mistakes ;)

**Comment by knqyf263** [comment]
I see.

It worked as you wrote.
Thank you very much!!
