### ISSUE TITLE
postgraphql not recognizing/finding stored procedures

### ISSUE THREAD

**Issue by tylerdmace** [postgraphql/postgraphql#529]
I'm having trouble getting a stored procedure to show up in graphiql and I'm not entirely sure why. What is the best practice here and what limitations come with trying to run stored procs from graphql?

**Comment by benjie** [comment]
Most important things are:

- make sure it doesn't return void
- make sure it's marked as stable (otherwise we'll think it's a mitation)
- make sure it's defined in one of the Postgres schemas you've told PostGraphQL to introspect

Feel free to share the definition if you want further help

**Comment by benjie** [comment]
Ah yes, sorry; I should have included that in the initial list. I'm going to edit it up there now. We don't have support for anonymous types right now (but I think you can create a type (`CREATE TYPE...`) as opposed to a full table?).

**Comment by tylerdmace** [comment]
Gonna give that a shot! I'll report back; Thank you for the quick replies. You rock.

**Comment by benjie** [comment]
Added to troubleshooting doc in https://github.com/postgraphql/postgraphql/pull/530

**Comment by tylerdmace** [comment]
Creating a custom data type worked just fine. Thanks again!

**Comment by benjie** [comment]
You're welcome!

**Comment by Remi-C** [comment]
Hey,
just a quick update.
I find it a bit unfair as some volatile functions do not change the data.
Anyway, there are workarounds.

**Comment by benjie** [comment]
What volatile function would you like to expose as if it were stable?

**Comment by Remi-C** [comment]
Some of my tables are actually foreign data wrapper,
so no guarantees on the data in it whatsoever.
Not really proper to set the functions using that to stable.
I can work around that though.

Le lun. 6 janv. 2020 à 14:36, Benjie Gillam <notifications@github.com> a
écrit :

**Comment by benjie** [comment]
> During a query that references any remote tables on a foreign server, postgres_fdw opens a transaction on the remote server if one is not already open corresponding to the current local transaction. The remote transaction is committed or aborted when the local transaction commits or aborts. Savepoints are similarly managed by creating corresponding remote savepoints.

> The remote transaction uses SERIALIZABLE isolation level when the local transaction has SERIALIZABLE isolation level; otherwise it uses REPEATABLE READ isolation level. This choice ensures that **if a query performs multiple table scans on the remote server, it will get snapshot-consistent results for all the scans**.

-- https://www.postgresql.org/docs/current/postgres-fdw.html#id-1.11.7.42.12 (emphasis mine)

> A `STABLE` function cannot modify the database and is guaranteed to return the same results given the same arguments for all rows **within a single statement**.

-- https://www.postgresql.org/docs/current/xfunc-volatility.html (emphasis mine)

A "single statement" always happens within a single transaction, so querying data from FDW is entirely valid as a `STABLE` function; and in fact should be marked as such for performance reasons.

**Comment by Remi-C** [comment]
Excellent, thanks @benjie !
