### ISSUE TITLE
Question: Stored Procedures best practices

### ISSUE THREAD

**Issue by colophonemes** [postgraphql/postgraphql#534]
My understanding is that PostGraphQL needs stored procedures to return exact table types in order to derive the relationship between the output of a stored procedure and related objects, e.g.

```sql
CREATE FUNCTION find_person_by_name(search_text TEXT) RETURNS SETOF person AS $$
...
$$ LANGUAGE SQL STABLE
```

However, to use `SETOF` entails a lot of `SELECT * FROM ...` in the stored procedure code. This is fine, but seems pretty universally [considered to be bad practice](https://stackoverflow.com/questions/65512/which-is-faster-best-select-or-select-column1-colum2-column3-etc). 

Is there an alternative way to write these procedures that works with PostGraphQL's relationship modelling that doesn't fall afoul of these issues? Or is this just the price of admission given the ease/flexibility of PostGraphQL? (Also very possible I'm missing something obvious, apologies if that's the case.)

**Comment by benjie** [comment]
In PostGraphQL v4 I don't think those concerns really apply at that level since we then select only the relevant fields from the result set; so only the fields we need are returned even though * may be referenced in the intermediate representation. I wouldn't be surprised if the query planner optimises it away, in fact.

In other words, I think you're safe to return * from a procedure so long as you select only the fields you need from the result:

```sql
select id, name from (select * from users where id < 100) as ref;
```

I'd be interested to see benchmarks that confirm or deny this.

**Comment by benjie** [comment]
(To be clear I'm talking about SQL benchmarks not PostGraphQL ones)

**Comment by colophonemes** [comment]
OK, so the effective query that PostGraphQL runs becomes something like:

```sql
SELECT full_name, id FROM find_person_by_name('my search string');
```
And that should be OK, even if `find_person_by_name` internally uses a `SELECT *`?

**Comment by colophonemes** [comment]
Also, version 4 isn't out yet, right? (Looks like `3.3.0` is current)

**Comment by benjie** [comment]
That was deliberate:

> The exception to this rule are simple SQL functions (LANGUAGE sql), which can be "inlined". Read more about how the query planner works in this presentation by Neil Conway (advanced stuff).

> -- https://dba.stackexchange.com/a/8189

However I would not take my word for it: if it's in an area where performance is a big deal then do some benchmarks and check. Honestly I'm not certain either way and would love to see some benchmarks.

V4 is almost ready, it's a ground-up rewrite of the schema generation and execution focussed on performance and extensibility, see: #506

**Comment by colophonemes** [comment]
Gotcha, many thanks for the detailed response!
