### ISSUE TITLE
Query for computed rows that does not exist in database?

### ISSUE THREAD

**Issue by pie6k** [postgraphql/postgraphql#536]
Problem: 
- make postgraphql return data that is not physically in database

Example:
- Consider calendar app. There is `event` table. There is single `event` 'go running' that is set to repeat every 3rd day.
- There is also table called `session` that is simply planned occurience of event. In theory, for event above - there is endless count of such task sessions, as it'll never end repeating. There is no way to save them all in database.
- Number of 'planned sessions', however - is countable - let's say user has moved *only one* single session to different hour. This 'planned sessions' will be indeed saved in database.

Now, I'd like to have custom function like `getSessionsForPeriodOfTime(start: Date, end: Date)` that would return 'computed' and 'saved' sessions together. 

How would you recommend to approach such situation?

**Comment by benjie** [comment]
You could create a function that returned a set of the table type - just because it returns the table type does not mean those rows have to actually exist - you can construct them on the fly, e.g.:

```sql
# \d post
                            Table "a.post"
  Column   |  Type   |                     Modifiers
-----------+---------+---------------------------------------------------
 id        | integer | not null default nextval('post_id_seq'::regclass)
 headline  | text    | not null
 body      | text    |
 author_id | integer |
Indexes:
    "post_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "post_author_id_fkey" FOREIGN KEY (author_id) REFERENCES person(id)

# select ('(,Hello,Body,)'::post).*;
 id | headline | body | author_id
----+----------+------+-----------
  ¤ | Hello    | Body |         ¤
(1 row)
```

An alternative way of doing it would be to implement the functionality in JavaScript using a library such as `rrule` and expose that functionality on the GraphQL schema using a graphql-build plugin for PostGraphQL v4 (currently in alpha, see #506).

**Comment by benjie** [comment]
To make my previous answer more complete, here's a function that creates a series of non-existent rows:

```sql
# create function post_series() returns setof post as $$ select (('(,Hello' || i || ',Body,)')::post).* from generate_series(1, 10) i; $$ language sql stable;
CREATE FUNCTION
Time: 14.705 ms
# select * from post_series();
 id | headline | body | author_id
----+----------+------+-----------
  ¤ | Hello1   | Body |         ¤
  ¤ | Hello2   | Body |         ¤
  ¤ | Hello3   | Body |         ¤
  ¤ | Hello4   | Body |         ¤
  ¤ | Hello5   | Body |         ¤
  ¤ | Hello6   | Body |         ¤
  ¤ | Hello7   | Body |         ¤
  ¤ | Hello8   | Body |         ¤
  ¤ | Hello9   | Body |         ¤
  ¤ | Hello10  | Body |         ¤
(10 rows)

Time: 0.475 ms
```

**Comment by pie6k** [comment]
@benjie thank! Would it be possible to compute those rows, when it'd require connecting to some microservice (asynchronously)?

eg. 
- it'd send function arguments to microservice over http
- serivice will respond with array of data
- it'll return data as proper table row `::session`
