### ISSUE TITLE
[Question] How is UpdatableView updated?

### ISSUE THREAD

**Issue by knqyf263** [postgraphql/postgraphql#537]
Thank you for the awesome tool!
I'm sorry to ask you many times.

I've tried `CREATE VIEW` in order to hide tables which have `created_at` and `updated_at`.
However, I couldn't get update and delete mutations.

I found `updatable_view` in the kitchen-sink example.
https://github.com/postgraphql/postgraphql/blob/master/examples/kitchen-sink/schema.sql#L52-L59
But even in this example, I got only `createUpdatableView` (and `allUpdatableViews`).

How do I get `updateUpdatableView` and `deleteUpdatableView`?
Do I have to create a function? Is `VIEW` only for select and insert?

```
postgres=# SELECT table_name, is_updatable, is_insertable_into FROM information_schema.views WHERE table_name = 'updatable_view';
   table_name   | is_updatable | is_insertable_into
----------------+--------------+--------------------
 updatable_view | YES          | YES
(1 row)
```

Thanks!

**Comment by benjie** [comment]
You need to read up on view rules/triggers; here's a few starting points:

https://www.postgresql.org/docs/current/static/trigger-definition.html
https://www.postgresql.org/docs/9.6/static/rules-update.html
https://www.postgresql.org/docs/9.6/static/rules-views.html
https://vibhorkumar.blog/2011/10/28/instead-of-trigger/

**Comment by knqyf263** [comment]
OK, I'll try to read up!
Thanks!
