### ISSUE TITLE
--watch Fails to set up fixtures

### ISSUE THREAD

**Issue by abegong** [postgraphql/postgraphql#546]
When I run `postgraphql --watch`, I get:

```
$ postgraphql --watch

PostGraphQL server listening on port 5000 🚀

  ‣ Connected to Postgres instance postgres://localhost:5432
  ‣ Introspected Postgres schema(s) public
  ‣ GraphQL endpoint served at http://localhost:5000/graphql
  ‣ GraphiQL endpoint served at http://localhost:5000/graphiql

* * *

Failed to setup watch fixtures in Postgres database ️️⚠️
This is likely because your Postgres user is not a superuser. If the
fixtures already exist, the watch functionality may still work.
```

Doing line by line execution of `watch-fixtures.sql`, I encounter this error:

```
# create event trigger postgraphql_watch
#   on ddl_command_end
#   when tag in (
#     'ALTER DOMAIN',
#     'ALTER FOREIGN TABLE',
#     'ALTER FUNCTION',
#     'ALTER SCHEMA',
#     'ALTER TABLE',
#     'ALTER TYPE',
#     'ALTER VIEW',
#     'COMMENT',
#     'CREATE DOMAIN',
#     'CREATE FOREIGN TABLE',
#     'CREATE FUNCTION',
#     'CREATE SCHEMA',
#     'CREATE TABLE',
#     'CREATE TABLE AS',
#     'CREATE VIEW',
#     'DROP DOMAIN',
#     'DROP FOREIGN TABLE',
#     'DROP FUNCTION',
#     'DROP SCHEMA',
#     'DROP TABLE',
#     'DROP VIEW',
#     'GRANT',
#     'REVOKE',
#     'SELECT INTO'
#   )
# 
# execute procedure postgraphql_watch.notify_watchers();
ERROR:  filter value "COMMENT" not recognized for filter variable "tag"
Time: 8.217 ms
```

After dropping COMMENT, GRANT, and REVOKE, the command executes. But of course that doesn't fix postgraphql itself, and I'm not sure we *want* to suppress triggers on those events.

What's the best way to get this to work? I'm doing a lot of DB schema work, so having `--watch` working is pretty critical.

Thanks!

PS: I'm running PostgreSQL 9.4.4 on a MacBook Air.

```
# SELECT version();
                                                                version                                                                
---------------------------------------------------------------------------------------------------------------------------------------
PostgreSQL 9.4.4 on x86_64-apple-darwin14.3.0, compiled by Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn), 64-bit
(1 row)

Time: 1.203 ms
```

**Comment by abegong** [comment]
When I edit `/usr/local/lib/node_modules/postgraphql/resources/watch-fixtures.sql`
and then CREATE a new table from within psql, I get this:

```
ERROR:  function pg_event_trigger_ddl_commands() does not exist
LINE 1: ...chema_name as schema, command_tag as command from pg_event_t...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT pg_notify( 'postgraphql_watch', (select array_to_json(array_agg(x)) from (select schema_name as schema, command_tag as command from pg_event_trigger_ddl_commands()) as x)::text )
CONTEXT:  PL/pgSQL function postgraphql_watch.notify_watchers() line 1 at PERFORM
Time: 5.896 ms
```

**Comment by benjie** [comment]
9.4.4 is pretty old, try upgrading to 9.6. We don't have feature detection yet but for PostGraphQL you're going to want at least 9.5 so you can use row level security policies, and probably even 9.6 so you can use missing_ok on the current_setting() function.

Also, watching works better in postgraphql@next because it successfully detects drops.

**Comment by abegong** [comment]
That did it. Is the requirement for 9.6 anywhere in the documentation?

**Comment by chadfurman** [comment]
@abegong not sure what version of postgraphql are / were on, however 9.4 is currently marked as the minimum required version for https://github.com/postgraphql/postgraphql/pull/506  -- I think this ticket is old and could be closed.

**Comment by benjie** [comment]
https://www.graphile.org/postgraphile/requirements/

Officially we only support --watch on 9.6+ - it's seen as a "nice to have" so we're okay with making people run PostgreSQL versions from the last 2 years to get it 🙂
