### ISSUE TITLE
Writing logs to an external file

### ISSUE THREAD

**Issue by SeenaLibin** [postgraphql/postgraphql#574]
Hi,
How can i write the logs in postgraphql console to an external file

**Comment by benjie** [comment]
Are you asking for something more than the following?

```
postgraphql > file.txt 2>&1
```

**Comment by SeenaLibin** [comment]
@benjie 
When postgraphql is up and we are running queries we can see the queries in console like

> 0 error(s) in 87.99ms :: { allDevelopers { edges { node { id } } } }

I want to write these logs to a external file and my postgraphql version is 3.2.0

**Comment by SeenaLibin** [comment]
@benjie 
I tried the above solution and it works perfect. Thanks a lot
