### ISSUE TITLE
Neither UUID nor Uuid works in v4 with `--dynamic-json` flag

### ISSUE THREAD

**Issue by freiit** [postgraphql/postgraphql#583]
I tested with the current branch of benjie/graphql-build.

It says under "breaking changes" that Uuid is now all in uppercase, but if I use this in a query or mutation, I get the error `message: 'Unknown type "UUID". Did you mean "ID"?'` Unfortunately leaving `Uuid` doesn't work either: `message: 'Unknown type "Uuid"`.

If I look with graphiql into the docs, I see the former `Uuid` as type `String`.

**Comment by benjie** [comment]
We have UUID in our tests, so this isn't a universal issue, you must be triggering some kind of bug...?

Test schema schema:

https://github.com/graphile/graphile-build/blob/master/packages/postgraphile-core/__tests__/kitchen-sink-schema.sql#L57

Snapshot showing it working:

https://github.com/graphile/graphile-build/blob/master/packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap#L100

Could you provide a pg_dump of a minimal schema that replicates UUID missing, please?

**Comment by benjie** [comment]
(`UUID` will only exist in your schema if it is used by something (a table column, a function argument, etc) - if you don't have one in your schema then you won't be able to use it in queries.)

**Comment by freiit** [comment]
I tried to create a minimal schema:
```
create database d1;
\c d1
begin;
create extension if not exists "pgcrypto";
create extension if not exists "uuid-ossp";
create schema cmx;
create role anonymous;
create type cmx.jwt as (
  role text,
  account_id uuid
);
create table cmx.account (
  myid uuid primary key default uuid_generate_v4(),
  name text not null
);
commit;
```
This results in that schema: https://gist.github.com/freiit/aa12258e8df01e4bb013e38570ed0569

myid is a `String!`, not a `UUID!`.

Tested with a fresh 9.6 postgres db and a freshly compiled version of the benjie/graphql-build branch.

**Comment by benjie** [comment]
Maybe there's something wrong with the way the code is being built? It's not really something I can debug from here since it works for me with the released version on `npm` which is built from the latest commit on the `benjie/graphql-build` branch:

![screenshot 2017-09-12 10 59 48](https://user-images.githubusercontent.com/129910/30320087-84fd1e62-97a9-11e7-8779-56c19ca35796.png)

This is using your schema above and running the latest postgraphql@next via:

```bash
npx postgraphql@next -c postgres://localhost/issue-583 --schema cmx
```

**Comment by benjie** [comment]
Do the tests pass for you? Run `npm test` - if they don't pass that may give an indication as to something being wrong with your setup - you can compare with travis: https://travis-ci.org/postgraphql/postgraphql/builds/274177299

**Comment by chadfurman** [comment]
Are you generating your schema with postgraphql / postgraphile?  I assume you are.

I also don't have this issue.  My UUID columns in my database are coming out as UUIDs.  For example:
```
  # The profile_id of the user who created the room.
  creatorId: UUID!
```

I'm on 4.0.0-alpha2.16

**Comment by chadfurman** [comment]
@freiit ^

**Comment by benjie** [comment]
I think @freiit's issue is related to building from source as opposed to using the compiled versions published to `npm`.

**Comment by freiit** [comment]
Guys, I started to doubt my test skills. For the protocol, I can reproduce the bug with the current `postgres@next` and all tests run through, when I use the `benjie/graphql-build` branch and `npm test` (with variable `TEST_PG_URL` set).

The missing piece is the parameter `--dynamic-json`. If you start your server with it, it does not show `UUID!`, but `String!`.

Can someone please confirm?

**Comment by benjie** [comment]
Can confirm - bug in `--dynamic-json` 👍

**Comment by benjie** [comment]
Published fix; confirmed working for me 👍

**Comment by freiit** [comment]
..that was a fast fix! Can confirm. Works now. Thanx. :+1:
