### ISSUE TITLE
[v4] null values ignored when creating objects

### ISSUE THREAD

**Issue by EyMaddis** [postgraphql/postgraphql#584]
Hi,
it is impossible to use `null` values when creating new objects, as it will be filtered out in the SQL insert.

I already created a [breaking test PR in graphile-build](https://github.com/graphile/graphile-build/pull/71).

```graphql
mutation insertMyType {
    createMyType(input: {
        myType: {
            id: "a fix id",
            nullableField: null
        }
    })  {
        myType {
            nullableField // => returns the default value from the database instead of "null"
        }
    }
}
```

will result in something like this (adapted by hand, maybe not perfect):

```sql
select set_config($1, $2, true), set_config($3, $4, true), set_config($5, $6, true), set_config($7, $8, true), set_config($9, $10, true)
with __local_0__ as (
    insert into "public"."my_type" (
        "id"
    ) values($1) returning *
)
select __local_0__::"public"."my_type" from __local_0__
```
Note the absence of "nullable_field".

This introduced a breaking change when switching from v3 to v4.

**Comment by benjie** [comment]
I guess we're doing a value check rather than a key check; though I'm not sure if the GraphQL specification actually differentiates between these two cases.

**Comment by EyMaddis** [comment]
@benjie it does: https://github.com/facebook/graphql/pull/83
