### ISSUE TITLE
Function With Parameters Gets Classified as a Mutation Instead of a Query

### ISSUE THREAD

**Issue by chris-guidry** [postgraphql/postgraphql#585]
I have some functions that return select queries based on input parameters and don't "mutate" any data. I would think these could/should be available as queries, but PostGraph treats them as mutations. Is there some way to modify such a function to show up as a query?

**Comment by benjie** [comment]
You need to mark the function as stable which informs postgres that it doesn't change anything.

https://www.graphile.org/postgraphile/custom-queries/

**Comment by chris-guidry** [comment]
Ah, great, thank you @benjie!
