### ISSUE TITLE
Default value "now()" is not applied on create, column set to null

### ISSUE THREAD

**Issue by cschroeter** [postgraphql/postgraphql#586]
Given the following schema:

```sql
create schema forum_example;

create table forum_example.user (
  id                     serial primary key,
  name               text not null check (char_length(name) < 80),
  created_at       timestamp default now() 
);
```

If I add a user like this

```sql
insert into forum_example.user (name) values ('Christian');
```

a valid user with an id, name and timestamp has been created.
But If i use graphiql with this mutation

```graphql 
mutation {
  createUser(input: {user: {name: "Christian"}}) {
    user {
      id
      name
      createdAt
    }
  }
}
```

the createdAt field is null.

**Comment by benjie** [comment]
Can you confirm which value of PostGraphQL you're using? Specifically I'm interested to know if the issue occurs in both `@latest` and `@next` or only one. You can run the specific versions via `npx` without messing up your environment; e.g.

```
npx postgraphql@latest -c postgres://...
```

```
npx postgraphql@next -c postgres://...
```

**Comment by cschroeter** [comment]
Works with @next not with @latest :)

**Comment by benjie** [comment]
I'm probably not going to fix it then; but if you wish to open a PR to fix this in v3 please do.

More information on `postgraphql@next` is available in #506; it's still in alpha currently but is already quite widely used and seems stable (though new versions might bring small breaking changes until it goes on general release).

**Comment by cschroeter** [comment]
Thanks for the fast response. I am fine with using @next version. 
Keep up the good work. It is an amazing library !

**Comment by benjie** [comment]
👍  Closing as fixed in v4.

**Comment by magom001** [comment]
Hi, I have the same issue. Using postgraphql 3.5.0 as a middleware. Column create_at default now() empty value when creating new rows from postgraphql.

**Comment by benjie** [comment]
I'd be happy to merge a PR that fixes this for v3. If you're happy running a late alpha, you can also try v4 with `npm install postgraphql@next` (see #506) but beware that (subtle) schema changes are still possible at this stage.

**Comment by magom001** [comment]
Sorry, Benjie! Just figured it out. Removed postgraphql from dependencies and installed postgraphile. Now it works like a charm.

**Comment by jamesho2877** [comment]
This works fine with the middleware but has not been applied for the CLI though.

**Comment by benjie** [comment]
What do you mean? The “postgraphile” CLI just calls the CLI middleware. If you think you’ve found a bug, please open a new issue.

**Comment by korenzerah** [comment]
Hello,
Is there a way to apply now() on a date time field on update without creating a trigger?

**Comment by benjie** [comment]
Trigger is the cleanest way to do it, but you could do something like this: https://www.graphile.org/postgraphile/plugin-gallery/#Mutation_wrappers__OverrideArgValuePlugin
