### ISSUE TITLE
Input validation in the middleware (additional scope required in `fieldWithHooks` call)

### ISSUE THREAD

**Issue by edqallen** [postgraphql/postgraphql#590]
After getting the example working thanks to #587 and searching here, I'm hitting a bump when trying to implement custom input validation in the middleware.  For various reasons, we would prefer not to do this in PG.  Ideally I'd like to be able to just intercept any update or create mutation and get a handle on the table/class name the mutation is targeting, and all the fields being sent in the patch.

The first half has been fairly straight forward after following along with the example using a bit of code like this:

`if ((0 == fieldName.indexOf('update')) || (0 == fieldName.indexOf('create'))) { /* stuff */ }`

I'm struggling to find a clean way to determine the name of the object/table being updated however.  Dumping the resolveParams (again, from the `resolve` method in the example) gives the patch pretty readily in the `input` field, but I need to know the class/table name, since it's named `fooPatch`.

Is there an easy way to get this information here, or am I taking the wrong approach entirely?

**Comment by benjie** [comment]
Sorry I cannot go into detail in this today, I can try and give some pointers though. When you hook up your override you have access to the Context object (the third argument passed to your hook) and within that is a field called “scope” which contains a field called “pgIntrospection” (or something like that, scan through the existing plugins for the correct name) which represents the entity (most likely table) the GraphQL object is being created for. This should tell you the table name, schema etc.

You should also be using this scope object to determine when to apply your resolve wrapper though I don’t know the fields to check for offhand

**Comment by benjie** [comment]
Actually it seems the fieldWithHooks call doesn’t add any context so it’s going to be harder to auto-detect. I’d consider a PR that adds pgIntrospection and isPgCreateField to the fieldWithHooks call so you can hook this more easily.

https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js

**Comment by edqallen** [comment]
@benjie I'm looking through and poking at the code you mentioned but it's not really clear to me what I should be doing.  I don't really have any experience in this sort of JS development, as until a week or two ago my experience was limited to purely client-side stuff with jquery et al.

Adding another parameter around line 232 (after the `getDataFromParsedResolveInfoFragment` block) doesn't cause any errors in the lerna tests, so is that the right approach/place to do this?

Sorry for the newbie questions but I want to make sure I'm on the right path here before I rebuild postgraphile and then start trying to hook into things in my application, since a mistake on the graphile side will leave me pointlessly scratching my head when debugging the express server.

**Comment by benjie** [comment]
So basically, the field with hooks call:

https://github.com/graphile/graphile-build/blob/d2da24040a6a352679b5985b4829634f32396e7a/packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js#L135-L140

...

https://github.com/graphile/graphile-build/blob/d2da24040a6a352679b5985b4829634f32396e7a/packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js#L220-L223

Only uses the call signature `fieldWithHooks(fieldName, spec)`. `fieldWithHooks` can be called with *3* arguments - the third one is `scope`:

https://www.graphile.org/graphile-build/context-object/#fieldwithhooksfieldname-spec-scope--

So if you were to insert an additional object just before line 222, the keys on that object would be available on the `context.scope` of the hook you write.

I would recommend passing `pgIntrospection: table` and maybe something like `isPgCreateMutationField: true` in a similar way to how the scope is passed to `newWithHooks` a few lines above:

https://github.com/graphile/graphile-build/blob/d2da24040a6a352679b5985b4829634f32396e7a/packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js#L124-L130


---

It's a shame the GitHub code embeds don't work cross-repository!

**Comment by benjie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ensure all `fieldWithHooks` calls declare the correct data on the third argument (scope)](https://trello.com/c/2A5QkxU8/13-ensure-all-fieldwithhooks-calls-declare-the-correct-data-on-the-third-argument-scope)

**Comment by benjie** [comment]
The next release of PostGraphile will include more scope information on many fields, and thus better hooks can be written 👍

**Comment by edqallen** [comment]
Benjie,

I'm revisiting this nearly a year later and without opening another ticket, I'm curious to know if any additional support for this sort of plugin has made it into the 4.0 branch?  An (over simplified) example of what I want to do would be to validate a value against a regex prior to the mutation making it to the DB.

TIA!

**Comment by benjie** [comment]
Yeah, sounds like you want to wrap the mutation resolvers:

https://www.graphile.org/postgraphile/extending/#wrapping-an-existing-resolver

Let me know what questions you have the docs don’t answer 👍

**Comment by edqallen** [comment]
That link was a big help, got the example sorted.  Before I continue, is this ticket the right place to continue this discussion?

All I want now is an easy way to get the name of the table I'm working on without the calling context on it -- e.g. reliably getting the name "Foo" from a mutation like "updateFooBySomeField" or "createFoo" or whatever.  I didn't see the name anywhere in the available data in the resolver wrapper.

**Comment by benjie** [comment]
Sorry about the poor documentation on this (help fixing it would be greatly appreciated once you've figured it out!); plugin hooks take three arguments `(thing, build, context)`; the `context` argument contains a `scope` property that tells you about the scope that the current hook is running in. This contains lots of useful information; I think you're either after `pgIntrospection` or `pgIntrospectionTable` which will tell you useful things about the thing that that field/type is based on. You're looking for one that has `.kind === 'class'`, like this:

https://github.com/graphile/graphile-build/blob/69d7b1cbe48ea5f50e3121916e7b1e12d1c70008/packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js#L46-L68

Here's an example from one of the built-in plugins:

https://github.com/graphile/graphile-build/blob/69d7b1cbe48ea5f50e3121916e7b1e12d1c70008/packages/graphile-build-pg/src/plugins/PgMutationPayloadEdgePlugin.js#L17-L35

**Comment by arenddeboer** [comment]
If you are using white-listed queries/mutations using for instance express middleware, validating the variables based on the matched query/mutation should be trivial. Upside is validation that is not tied into PostGraphile/PG, downside is you may have to repeat validation for every white-listed query instead of reusable field-level validation.

**Comment by ken0x0a** [comment]
https://www.graphile.org/postgraphile/plugin-gallery/#Mutation_wrappers__OverrideArgValuePlugin

Changing this, and possible create reusable args validation plugin ( not yet created though ).

```ts
return {
      ...field,
      resolve(mutation, args, context_2, info) {
        args.input.patch = editProfileSchema.validateSync(args.input.patch)
        console.log('\n\n\n\x1b[36m%s\x1b[0m', 'here should not be called\n\n\n') // here not called and 

        return oldResolve!(mutation, args, context_2, info)
      },
    }
```

this returns

```json
{
  "errors": [
    {
      "message": "username must be at most 10 characters",
      "locations": [
        {
          "line": 137,
          "column": 3
        }
      ],
      "path": [
        "updateUserById"
      ]
    }
  ],
  "data": {
    "updateUserById": null
  }
}
```

perfect!!
