### ISSUE TITLE
Non-nullable tstzrange throws error instead of using default value

### ISSUE THREAD

**Issue by Hesulan** [postgraphql/postgraphql#612]
### Example table
```sql
create table test (
  "id" serial primary key,
  "test_text" text,
  "test_period" tstzrange not null default tstzrange(current_timestamp, null)
);
```
### Example query
```graphql
mutation CreateTest($input: CreateTestInput) {
  createTest(input: $input) {
    test { id }
  }
}
```
### Example query variables
```json
{
  "input": {
    "test": {
      "test_text": "test"
    }
  }
}
```

### Expected result
A new record should be created using the default value for "test_period".

### Actual result
```json
{ "errors": [ { "message": "Input value must be an object, not 'undefined'." } ] }
```

> Note: Making the field nullable prevents the error, but that's not a real solution, and it's not possible in my specific use-case.

### On a related note...
`TimezoneTimestampRangeBoundInput` requires both `value` and `inclusive`, but PostgreSQL defines default exclusivity values for each range type (`tstzrange` defaults to start inclusive, end exclusive), and it does allow `null` as a start or end value.

**Comment by benjie** [comment]
What's `postgraphql --version` ?

**Comment by benjie** [comment]
I have a feeling this is fixed in v4.

**Comment by Hesulan** [comment]
@benjie Yep! You were right, just tried it with v4 and it worked. Thanks!

P.S.: My related note about ranges allowing `null` seems unchanged. I'm not sure if that's even handled by PostGraphQL directly, just thought I should mention it because that's the main way that PostgreSQL range types represent "infinity".

**Comment by benjie** [comment]
I believe value is nullable in v4 for this reason? If not can you give a code example of exactly how v4 is wrong? Thanks 🙏

**Comment by Hesulan** [comment]
@benjie Ah, it seems the "value" property is still non-nullable in v4 (`DatetimeRangeInputBound { value: Datetime!, interval: Datetime! }`), but both the "start" and "end" bounds *themselves* are now optional (`DatetimeRangeInput { start: DatetimeRangeInputBound, end: DatetimeRangeInputBound }`). Since `null` bounds are always non-inclusive, excluding it has the same result as passing an explicit `null`.

Still, might be a good idea to make at least the "value" property nullable anyway. That's how PostgreSQL treats it, and it would - for example - allow someone to take the output from a query (`{"value":null,"inclusive":false}`) and feed it directly into the input of a mutation without receiving a strange and unnecessary error.

> Note: I've only confirmed this behavior with `tstzrange` and `numrange`, but I assume it holds true for all built-in range types.

**Comment by benjie** [comment]
Ah yes, I knew there was some subtlety here. I decided that the difference between including infinity and excluding infinity was such an edge case that it would be better to not worry about it (since you can't express infinity through GraphQL anyway the point seemed moot). So in PostGraphile ranges can be unbounded but we don't differentiate between `[-Infinity, 0)` and `(-Infinity, 0)`

**Comment by Hesulan** [comment]
It's definitely an edge case, but it might be worth noting that PostgreSQL actually considers `Infinity` a *bounded* range:
```sql
select lower_inf(r), upper_inf(r) from tstzrange(null,null) # true,true
select lower_inf(r), upper_inf(r) from tstzrange('-Infinity','Infinity') r; # false,false
```

I checked and PostGraphQL does allow `{"value":"infinity", ...}`, though as you said it doesn't actually handle it differently. I would still recommend making "value" nullable, if only to keep input and output consistent.

Anyway, thanks for the help! Still getting the hang of PostGraphQL (and GraphQL in general) but so far I'm loving it, especially not having to redesign my database schema. Keep up the good work! :)

**Comment by benjie** [comment]
Yeah; I had to decide between:

> Q: Does it have an upper bound?  
> A: Yes, it's non-inclusive but its value is null which implies infinity

And:

> Q: Does it have an upper bound?
> A: No.

The former models the data represented in PostgreSQL better, but the latter is much less surprising for a human in my opinion so I went with that. If there's sufficient demand to change it then I'm definitely open to doing so, this is just the decision I made at the time.
