### ISSUE TITLE
Forum example may have security issue

### ISSUE THREAD

**Issue by timwis** [postgraphql/postgraphql#624]
I could be wrong here, but I think the forum example's row-level security settings allow someone to `update` their `post` to change its `author_id` to someone else, thereby posting on their behalf.

```sql
create policy update_post on forum_example.post for update to forum_example_person
  using (author_id = current_setting('jwt.claims.person_id')::integer);
```

should be something like (with @benjie's input from gitter)
```sql
create policy update_post on forum_example.post for update to forum_example_person
  using (author_id = current_setting('jwt.claims.person_id')::integer)
  with check (author_id = current_setting('jwt.claims.person_id')::integer);
```

I'm rather inexperienced with row-level security, though, so I could be wrong here. Just want to point it out in case I'm right :/

**Comment by benjie** [comment]
I don't think that's necessary in this case (emphasis mine):

> For policies that can have both USING and WITH CHECK expressions (ALL and UPDATE), **if no WITH CHECK expression is defined, then the USING expression will be used** both to determine which rows are visible (normal USING case) and which new rows will be allowed to be added (WITH CHECK case).
> -- https://www.postgresql.org/docs/9.5/static/sql-createpolicy.html

i.e. if `WITH CHECK` is omitted then the `USING` clause will also apply to `WITH CHECK`.

**Comment by timwis** [comment]
Cool, thanks!
