### ISSUE TITLE
allow options to be passed to jwt.verify()

### ISSUE THREAD

**Issue by wenzowski** [postgraphql/postgraphql#625]
I'm submitting a ... 
- [ ] bug report
- [x] feature request
- [ ] question 

PostGraphQL version:

4.0.0-alpha2.22

There's currently no way to pass options to `jwt.verify()` as the options object is a hardcoded `{audience: jwtAudiences}` and it would be ideal to be able to spread important configuration options into that...options like`{clockTolerance: 1}`.

**Comment by benjie** [comment]
That should be fairly easy to add:

Pass through the new setting from the `options` variable here:

https://github.com/postgraphql/postgraphql/blob/273ae4b0ae40d50bcc6c2874711ced3beb683aa0/src/postgraphql/http/createPostGraphQLHttpRequestHandler.js#L404-L411

e.g.

```js
jwtVerifySettings: options.jwtVerifySettings,
```

destructure it here:

https://github.com/postgraphql/postgraphql/blob/273ae4b0ae40d50bcc6c2874711ced3beb683aa0/src/postgraphql/withPostGraphQLContext.ts#L35-L41

pass it through here:

https://github.com/postgraphql/postgraphql/blob/273ae4b0ae40d50bcc6c2874711ced3beb683aa0/src/postgraphql/withPostGraphQLContext.ts#L65-L71

and splat it out here:

https://github.com/postgraphql/postgraphql/blob/273ae4b0ae40d50bcc6c2874711ced3beb683aa0/src/postgraphql/withPostGraphQLContext.ts#L129

A pull request would be welcome - I'd like to see tests with it.

**Comment by skvale** [comment]
Fixed by #655
