### ISSUE TITLE
numeric overflow

### ISSUE THREAD

**Issue by wenzowski** [postgraphql/postgraphql#630]
I'm submitting a ...
- [x] bug report
- [ ] feature request
- [ ] question

PostGraphQL version:
`4.0.0-alpha2.22`

Minimal SQL file that can be loaded into a clean database:
``` sql
CREATE TABLE example (big_number NUMERIC);
```

Steps to reproduce:
```
mutation ($input: CreateExampleInput!) {
  createExample(input: $input) {
    clientMutationId
  }
}
```
```
{
  "example": {
    "bigNumber": "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"      
    }
  }
}
```
```
{
  "errors": [
    {
      "message": "invalid input syntax for type numeric: \"Infinity\"",
      "path": [
        "createExample"
      ],
      "errcode": "22P02",
    }
  ],
  "data": {
    "createExample": null
  }
}
```

### Current behavior:
String is cast to floating point presumably through `Number.parseFloat()` before being passed to the `numeric` column. This is surprising given [`numeric` supports up to 131072 digits before the decimal point; up to 16383 digits after the decimal point](https://www.postgresql.org/docs/current/static/datatype-numeric.html).

### Expected behavior:
 The [recommended graphql approach](https://github.com/graphql/graphql-js/issues/292) is to handle large numbers as strings and was the solution to #302. Perhaps the input could be sanitized with something like [decimal.js](https://github.com/MikeMcl/decimal.js/). Let's please not implement this with `Number.isSafeInteger()` because users of `numeric` are could be using it to avoid IEEE 754 rounding errors.

**Comment by benjie** [comment]
Numerics should be strings; this is likely a bug in https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js

In fact, yes, it's this line:

https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js#L234

Basically if we detect it as anything with [pg type category](https://www.postgresql.org/docs/9.6/static/catalog-pg-type.html#CATALOG-TYPCATEGORY-TABLE) 'N' we treat it as a GraphQLFloat. We should change that line to GraphQLString; but in doing so we'll have to be extra careful that we have int/float detection in place for types that *are* able to be parsed into a 8-byte float or 53-bit integer e.g. `float8`, `float4`, `float2`, `int4`, `int2` and certain numerics depending on their definitions. This was just me rushing through at the very beginning to get a bare-bones version that mostly worked and I've not yet gone back through and padded out the remaining work required.

If you're up for writing a pull request for this, that would be grand!

**Comment by wenzowski** [comment]
For the smaller types I would imagine we could rely on pg to throw `ERROR: integer out of range` on input overflow?

**Comment by benjie** [comment]
```
select '10000000'::int2;
ERROR:  22003: value "10000000" is out of range for type smallint
LINE 1: select '10000000'::int2;
               ^
LOCATION:  pg_atoi, numutils.c:81
```

Looks like it.

**Comment by benjie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Numeric overflow](https://trello.com/c/vPsJntkn/11-numeric-overflow)

**Comment by benjie** [comment]
This is now fixed.
