### ISSUE TITLE
Can the PostGraphQL endpoint be used to create a SOAP request

### ISSUE THREAD

**Issue by Tritpi** [postgraphql/postgraphql#633]
Can the PostGraphQL endpoint that is served at  http://localhost:5000/graphql be used to generate a SOAP request such that the query to be made can be passed in the parameters in the SOAP request and the data that comes back in the GraphiQL interface will come as an xml.

**Comment by benjie** [comment]
This is outside the scope of the project; but you should be able to insert a middleware in front of PostGraphQL (or *any* GraphQL server, this is not specific to PostGraphQL) that does SOAP <--> GraphQL conversion using GraphQL's built in introspection.
