### ISSUE TITLE
Automatically rename tables that end with `_input` so they don't clash with input types

### ISSUE THREAD

**Issue by tapsaid** [postgraphql/postgraphql#647]
I'm submitting a ... 
- [ ] bug report
- [ ] feature request
- [x ] question 

PostGraphQL version:

Minimal SQL file that can be loaded into a clean database:
``` sql

```

Steps to reproduce:

Create a table which has the word "input" as a suffix. 

Current behavior:
Error: Schema must contain unique named types but contains multiple types named "HrPayslipInput".
(I guess this is because I have table named hr_payslit_input)

Expected behavior:
Since I'm not the designer of the database(I would like to use postgraphql to generate queries for Odoo 9 database), I expect the generator to work by taking this exceptional case.

A workaround would also be welcomed.

**Comment by benjie** [comment]
We could potentially solve this automatically by taking tables that end in reserved words (such as `input`) and giving them extra text. e.g. table `foo_input` might become `type FooInputTable` or `type FooInput_` or ...

I'm not sure what it *should* become - ideas welcome.

**Comment by benjie** [comment]
As for a workaround; you can override the inflector in v4 and then rename specifically that table; see this comment:

https://github.com/postgraphql/postgraphql/pull/506#issuecomment-328831456

Sorry there's not much docs on that yet.

**Comment by tapsaid** [comment]
Without documentation I could hardly manage to get it right. Anyway, thanks for the direction.

**Comment by benjie** [comment]
A pull request updating the docs with this caveat would be welcome. The relevant page is here:

https://www.graphile.org/postgraphile/custom-mutations/

(See also the computed columns docs here: https://www.graphile.org/postgraphile/computed-columns/)

You can edit it here:

https://github.com/graphile/graphile.github.io/edit/develop/src/pages/postgraphile/custom-mutations.md

**Comment by benjie** [comment]
Whoops, mistook this issue for the wrong one - ignore previous comment.

**Comment by benjie** [comment]
For anyone interested in doing a PR for this (should be quite easy), you just need to modify this function:

https://github.com/graphile/graphile-build/blob/83abbb84d62415a6ff455426e9424a61d95a815b/packages/graphile-build-pg/src/inflections.js#L90-L92

so that if the resulting type name ends with a reserved word (e.g. `Input`) it has something else suffixed to it. As above I'm not sure what the suffix should be.

e.g.

```js
      tableName(name: string, _schema: ?string) {
        return camelCase(singularize(name)).replace(/(Input|Patch)$/, '$&Table');
      },
```
