### ISSUE TITLE
Error when calling a function with a custom type parameter, or with a parameter of a type colliding with another mutation

### ISSUE THREAD

**Issue by wizeowl** [postgraphql/postgraphql#649]
I'm submitting a
- [x] bug report
- [ ] feature request
- [ ] question 

PostGraphQL version:
4.0.0-alpha2.25

Minimal SQL file that can be loaded into a clean database:
``` sql
CREATE SCHEMA sales;

CREATE TABLE sales.customer (
  id               SERIAL PRIMARY KEY,
  ref              TEXT NOT NULL CHECK (char_length(ref) < 255),
  idCompte         TEXT NOT NULL UNIQUE CHECK (char_length(idCompte) < 255),
  categorie        TEXT NOT NULL CHECK (char_length(categorie) < 255),
  nom              TEXT NOT NULL CHECK (char_length(nom) < 255),
  prenom           TEXT NOT NULL CHECK (char_length(prenom) < 255)
);

CREATE TABLE sales.livreur (
  id               SERIAL PRIMARY KEY,
  nom              TEXT NOT NULL CHECK (char_length(nom) < 255),
  img              TEXT,CASCADE ON DELETE SET NULL
);

CREATE TABLE sales.bl (
  id               SERIAL PRIMARY KEY,
  cust_id          TEXT REFERENCES sales.customer (idCompte) MATCH SIMPLE ON UPDATE CASCADE ON DELETE SET NULL,
  livreur_id       INTEGER REFERENCES sales.livreur (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE sales.bl_line (
  id               SERIAL PRIMARY KEY,
  count            INTEGER   DEFAULT 1,
  bl_id            INTEGER REFERENCES sales.bl (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TYPE sales.full_bl AS (
  new_bl    sales.bl,
  new_lines sales.bl_line []
);

CREATE OR REPLACE FUNCTION sales.create_full_bl(full_bl sales.full_bl)
  RETURNS VOID AS $$
DECLARE
  bl       sales.bl;
  new_line sales.bl_line;
BEGIN
  INSERT INTO sales.bl (cust_id, livreur_id) VALUES
    (full_bl.new_bl.cust_id, full_bl.new_bl.livreur_id)
  RETURNING *
    INTO bl;

  FOREACH new_line SLICE 1 IN ARRAY full_bl.new_lines
  LOOP
    INSERT INTO sales.bl_line (bl_id, product_id, count) VALUES
      (bl.id, new_line.product_id, new_line.count);
  END LOOP;
END;
$$ LANGUAGE plpgsql;

```

Steps to reproduce: I call the mutation
```
mutation {
  createFullBl(input: {fullBl: {newBl: {custId: "UNIB0001", livreurId: 5}, newLines: []}}) {
    clientMutationId
  }
}
```
Current behavior:
```
{
  "errors": [
    {
      "message": "missing FROM-clause entry for table \"new_bl\"",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createFullBl"
      ]
    }
  ],
  "data": {
    "createFullBl": null
  }
}
```
Expected behavior:
The I believe you are much more apt than me to make sense of the error above.

Second You may notice that I used a custom type (sales.full_bl) as the argument for the function. The reason is that when I originally used the declaration below, Postgraphql didn't create the mutation. Like any "good developer" I restarted the server again and again scouring the graphiql interface everytime for the createFullBl endpoint but to no avail. Life quality basically went downhill.
```sql
CREATE OR REPLACE FUNCTION sales.create_full_bl(new_bl sales.bl, new_lines sales.bl_line [])
```

**Comment by benjie** [comment]
Interesting, not seen that issue before. Seems to be when a compound type of a compound type is used as an input value. Please can you reduce your schema and query down to the smallest you can that reproduces the issue? If you’re able, creating a failing test would also be excellent, see:

https://github.com/postgraphql/postgraphql/issues/648

**Comment by benjie** [comment]
Deleting the function body reveals that the issue lies in your function rather than in PostGraphQL - running the function with an empty body works fine.

The issue is the way in which you are referencing the field off the composite type, you need additional brackets, i.e.

```sql
  INSERT INTO sales.bl (cust_id, livreur_id) VALUES
    ((full_bl.new_bl).cust_id, (full_bl.new_bl).livreur_id)
```

See [8.16.3. Accessing Composite Types](https://www.postgresql.org/docs/9.6/static/rowtypes.html) in the PostgreSQL documentation for an explanation and more information.

I'm relieved this isn't a bug in PostGraphQL, I was not looking forward to fixing it! 😅

**Comment by wizeowl** [comment]
First of all, thank you so much. the issue was solved.
Second, though it's arguably a surmountable hindrance, I nevertheless still wonder why the other function definition couldn't be generated into an endpoint.
Finally, keep the good work, and high five for the great piece of software.

**Comment by benjie** [comment]
Ah; I suspect the reason for that is it’s falling foul of the “computed column” detection. We’re currently reserving that in case we come up with a way of making computed columns settable but we may well release it in future. I think it only affects when a table type is used as the first input.
