### ISSUE TITLE
List of PostGraphQL as a service options

### ISSUE THREAD

**Issue by ppKrauss** [postgraphql/postgraphql#656]
Hi, it is a suggestion to **add a new markdown file or CSV file** in this git repository, <br/>with a **list of current  "PostGraphQL as a service"** ([SaaS](https://en.wikipedia.org/wiki/Software_as_a_service)) suppliers.

----

PS: services like Heroku Postgres, Amazon/PostgreSQL,  Azure/PostgreSQL, etc. in nowadays not offer  PostGraphQL.. And it is difficult to find one that offers.

**Comment by benjie** [comment]
A wiki page would be a good place for that. I’m not aware of any generic PostGraphQL SaaS, though I am aware of a few people building platforms around it.

I’m closing this just to keep things tidy, but please feel free to keep discussing.

**Comment by ppKrauss** [comment]
Hi @benjie , thanks!  Can you add one item into [the table at Wiki](https://github.com/postgraphql/postgraphql/wiki/Infrastructure-as-a-Service)?  Perhaps you know a "potential" one, so we can negotiate negotiate to expedite/simplify the service.
