### ISSUE TITLE
PGPASS Environment Variable Support

### ISSUE THREAD

**Issue by antmldr** [postgraphql/postgraphql#657]
I'm submitting a ... 
- [ ] bug report
- [x] feature request
- [ ] question

It'd be useful for postgraphql to be able to utilize the PGPASS environment variable, if present, when building its connection string (see: [cli.ts](https://github.com/postgraphql/postgraphql/blob/master/src/postgraphql/cli.ts#L102))

Is this something appropriate for v3 or v4?
Would it be something the project would be open to a PR for? I'd be happy to implement & test it.

**Comment by benjie** [comment]
PR welcome; do it against v3 only (master) - I’ll merge to v4 later. Ensure it still functions correctly if the envvar is not set (e.g. check `{username: undefined}` is treated the same as if the key were omitted: `{}` (failing that, use Object.assign or similar  to only add each key if the envvar is set)

Thanks!

**Comment by antmldr** [comment]
Awesome, thanks for merging & your guidance here!
