### ISSUE TITLE
Set user_id fkey / userId input field from auth data 

### ISSUE THREAD

**Issue by dradetsky** [postgraphql/postgraphql#662]
I'm submitting a ... 
- [ ] bug report
- [x] feature request
- [ ] question 

PostGraphQL version:
```
% postgraphile --version
4.0.0-alpha2.27
```
My app has a fair number of tables where each row has to have an `owner_id`, a foreign key into a `users` table. It also has some kind of authentication so that incoming messages have a bearer token from which we infer (among other things) a `user_id`.

In general, I want it to be the case that:

- a user cannot affect the owner_id of any record, including those he creates.
- when a user creates a record, we set `owner_id=user_id`

Because there are a fair number of these tables, and they don't have much of interest going on by themselves, I'd like to autogenerate the CRUD mutations for them instead of writing them myself.

But when postgrap(ile|ql) introspects the database it sees that:

- there is a field here called `owner_id`, so we should permit & use the user-supplied `ownerId`.
- the field `owner_id` is non-nullable, so we should _require_ the user to supply `ownerId`

Which is the opposite of what I want.

My proposed solution: make a plugin called something like `PgSettingsToMutationInput` which would consume some kinda config file where I could define mappings between postgres config settings (like `jwt.claims.user_id`) and mutation fields (like `ownerId`). If I create such a mapping for a field, the introspector should not make that field part of the api (or possibly, via a flag, make it not a required field).

**Comment by benjie** [comment]
I think it’s easier to solve it than that:

- don’t allow that column to be inserted or updated (sql grant/revoke)
- set the sql default for that column to be `get_setting(‘jwt.claims.user_id’, true)`

That should be all that’s necessary, hopefully?

**Comment by dradetsky** [comment]
Yes, that works fine.

It does leave the (unusable) `ownerId` field in the public `CreateFooInput` type, but I understand there's a separate way of cleaning up the publicly-exposed api.

**Comment by benjie** [comment]
Yes, there’s the undocumented pgColumnFilter. We hope to make this more automatic in future.

**Comment by dradetsky** [comment]
btw, until you write more dox, you might mention for the benefit of future readers that it's `current_setting('jwt.claims.user_id')`, not `get_setting`
