### ISSUE TITLE
Option to auto-quit Postgraphile CLI (e.g. to simply export schema)

### ISSUE THREAD

**Issue by danvk** [postgraphql/postgraphql#666]
I'm submitting a ... 
- [ ] bug report
- [x] feature request
- [ ] question 

PostGraphQL version: 4.0.0-alpha2.28

When I run `postgraphile` with the `--export-schema-json` option, it still starts a server:

```
$ postgraphile --schema explorer --export-schema-json schema/schema.json

PostGraphQL server listening on port 5000 🚀

  ‣ Connected to Postgres instance postgres://localhost:5432
  ‣ Introspected Postgres schema(s) explorer
  ‣ GraphQL endpoint served at http://localhost:5000/graphql
  ‣ GraphiQL endpoint served at http://localhost:5000/graphiql

* * *
...
```

I'd like to _just_ export the schema that it discovers for my database. It would be helpful if there were, say, a `-q` / `--quit` option which made the CLI do the exporting without starting the server. This would be helpful for running it in a script (to generate TypeScript definitions for my GraphQL schema) and for running it in a CI environment (where I'd like to verify that the the generated types are up-to-date).

**Comment by benjie** [comment]
We need this for a few other commands too. How about --no-server?

**Comment by benjie** [comment]
A PR for this would be welcome

**Comment by wenzowski** [comment]
> for running it in a CI environment (where I'd like to verify that the the generated types are up-to-date)

So would CI workflow end up looking something like
```
postgraphile --no-server --schema explorer --export-schema-json schema/schema.json
git diff --exit-code schema/schema.json
```

**Comment by benjie** [comment]
`--no-server` / `-X` added; works with `--watch` as you'd expect 👍
