### ISSUE TITLE
Cant connect to postgraphile server

### ISSUE THREAD

**Issue by Superpat** [postgraphql/postgraphql#684]
I'm submitting a ... 
- [x] bug report
- [ ] feature request
- [ ] question 

PostGraphQL version: 4.0.0-alpha2.30

Running in alpine linux 3.7 under openbsd 6.2 vmm
I've verified that I'm able to access other servers on the guest and I've tried other ports.

Minimal SQL file that can be loaded into a clean database: https://github.com/postgraphql/postgraphql/blob/master/examples/forum/schema.sql
Steps to reproduce:

Current behavior:
`postgraphile -c postgres://postgres@localhost/graphile -s forum_example --secret keyboard_kitten --default-role forum_example_anonymous` opens a server but I cant access it.

Expected behavior:
Being able to access it.

![2018-02-14-170017_3840x1080_scrot](https://user-images.githubusercontent.com/4533283/36230801-9de044fc-11a9-11e8-8fb5-e5592752477e.png)

**Comment by benjie** [comment]
Server is running on localhost but you’re connecting to 10.13.37.35; to bind to all addresses use `--host 0.0.0.0` see https://www.graphile.org/postgraphile/usage-cli/

**Comment by Superpat** [comment]
Thanks, thought it would be for a stupid reason, but I missed it in the docs. fixed it.
