### ISSUE TITLE
orderBy On Multiple Columns

### ISSUE THREAD

**Issue by sstubbs** [postgraphql/postgraphql#691]
First of all thank you for the brilliant work on this. It really is great.

I am trying order by multiple columns with one of the standard queries generated. From what I can tell it seems to only work for one column. If I add two orderBy arguments I get an error

There can be only one argument named \"orderBy\"."

and it does not accept an array either. So is this functionality planned? I would rather not have to create custom Postgres functions for something this minor so if not perhaps I can do a plugin for it. I am using the filter plugin https://github.com/mattbretl/postgraphile-plugin-connection-filter which works really well and I am happy to contribute but I would need a bit of help getting started with this.

**Comment by benjie** [comment]
What version are you using? The latest postgraphile should support orderBy array.

**Comment by sstubbs** [comment]
ok great thank you I will try and upgrade. I am using 4.0.0-alpha2.22

**Comment by sstubbs** [comment]
I have upgraded to the latest version and it does accept an array. Thank you very much.
