### ISSUE TITLE
Support passing a pg client to createPostGraphQLSchema

### ISSUE THREAD

**Issue by mshick** [postgraphql/postgraphql#692]
I'm submitting a ... 
- [ ] bug report
- [x] feature request
- [ ] question 

PostGraphQL version:
4.0.0-alpha2.33

It would great if you supported passing a `pg` client to `createPostGraphQLSchema`. In addition to removing potential version conflicts, it would allow users to use `pg-native` if their system handles it.

**Comment by benjie** [comment]
Is there a reason we need to support a client as opposed to a pool? For example this will create a pool, but only one connection (client) will be made and it will be released afterwards:

```js
const { Pool, native: { Client: NativeClient } } = require('pg');

async function getSchema() {
  const nativePool = new Pool({ Client: NativeClient });
  const schema = await createPostGraphQLSchema(
    nativePool,
    "my_schema",
    {...options}
  );
  await nativePool.end();
  return schema;
}
```

(Written directly into GitHub, so may not work as written.)

**Comment by mshick** [comment]
@benjie I'm very sorry. I just reviewed the latest code and noticed you're already supporting this (or at least, you're supporting what I needed — passing my own pool in).

Apologies for the false alarm.

Awesome project btw, I just dove into it today and am blown away. Thanks!

**Comment by benjie** [comment]
No problem - clearly something to improve in the docs 👍
